govuk-one-login/onboarding-self-service-experience

express/src/app.ts, express/src/controllers/create-account.ts, express/src/controllers/sign-in.ts, express/src/lib/cognito.ts, express/src/lib/cognito/CognitoInterface.ts, express/src/middleware/authoriser.ts, express/src/routes/create-account-or-sign-in.ts, express/src/routes/manage-account.ts
Use sign-in form to sign user in and store token in session. Correct incorrect capitalisation of AuthenticationResult which meant the tokens were never stored.
Create basic authoriser middleware to check for presence of token and render login page if token missing.
Add authoriser middleware to router for list-services controller so that users must be logged in to view this screen.
Separate login with temporary password from display of change password view so it can be more easily re-used.
=> DFA-691 Create Login Process

.github/workflows/build.yml, .github/workflows/deploy-branch.yml, .github/workflows/deploy-to-paas.yml
=> Dfa 858 preview environment

lambda/dynamo-api/deploy-script.sh, lambda/dynamo-api/src/client/DynamoClient.ts, lambda/dynamo-api/src/handlers/get-service-clients.ts, lambda/dynamo-api/template.yaml
Create lambda that calls function of DynamoClient
Add function to DynamoClient
Update SAM template
Remove unecessary parameters from deploy script.
=> DFA-941 Get sevice-clients for a service lambda

express/src/controllers/create-account.ts, express/src/controllers/manage-account.ts, express/src/lib/lambda-facade/LambdaFacade.ts, express/src/lib/lambda-facade/LambdaFacadeInterface.ts, express/src/lib/lambda-facade/StubLambdaFacade.ts, express/src/routes/manage-account.ts, express/src/routes/testing-routes.ts, express/src/views/dashboard/change-client-name.njk, express/src/views/dashboard/change-post-logout-URIs.njk, express/src/views/dashboard/change-public-key.njk, express/src/views/dashboard/change-redirect-URIs.njk, express/src/views/dashboard/change-user-attributes.njk, express/src/views/dashboard/client-details.njk, lambda/dynamo-api/src/handlers/put-service-client.ts, lambda/dynamo-api/template.yaml
Add listClients method to LambdaFacade
Update various client related views and controllers to deal with clientId path parameters.
There's a good chance we'll need to go `change-whatever/:serviceId/:clientId` to make things easier but this is enough for now to display things.
=> DFA-942 get service clients and enable their display

express/assets/css/app.scss, express/src/routes/testing-routes.ts, express/src/views/account/account.njk, express/src/views/layout-dashboard.njk
Create Account Profile page front-end
=> DFA-1460: Create Account Profile page front-end

express/src/routes/testing-routes.ts, express/src/views/account/change-service-name.njk
Create 'change your service name' page
View and testing route for 'change your service name' page
=> DFA-1484 Create 'change your service name' page

express/assets/css/app.scss, express/src/routes/testing-routes.ts, express/src/views/dashboard/change-public-key-v2.njk
Create frontend for 'Change your public key' page, updated version, including error messages display.
=> DFA-1458: Create frontend for 'Change your public key' page, updated version

express/src/routes/testing-routes.ts, express/src/views/account/change-phone-number.njk
Create 'Change your mobile number' page frontend
=> DFA-1482 - Create 'Change your mobile number' page frontend

express/src/views/layout-dashboard.njk
Update top navigation links for signed in user
=> DFA-1526 Update top navigation links for signed in user

express/assets/javascripts/show-password-two-fields.js, express/package.json, express/src/routes/testing-routes.ts, express/src/views/account/change-password.njk
Create 'Add your new password' page
=> DFA-1494 Create 'Add your new password' page

express/src/routes/testing-routes.ts, express/src/views/dashboard/private-beta-form-submitted.njk
Create 'form submitted' page frontend
=> DFA-1476 Create 'form submitted' page frontend

express/features/mobile-verification-resend.feature, express/features/support/steps/email-verification-resend-steps.ts, express/features/support/steps/mobile-verification-resend-steps.ts, express/features/support/steps/sign-in-steps.ts, express/features/valid-email-domains.feature, express/src/controllers/create-account.ts, express/src/middleware/emailValidator.ts, express/src/views/create-account/enter-mobile.njk, express/src/views/create-account/get-email.njk, express/src/views/create-account/new-password.njk, express/src/views/sign-in.njk, express/stubs-config.json, express/valid-email-domains.txt
Add domains to text file.
Modify code so that .gov.uk needs to be in the text file but socialworkengland.org.uk is fine.  This stops sneakygov.uk from working.
Do stuff to have email address appear if user goes back after submitting.
Write tests.
Do a ton of stuff to get tests to work, including existing tests.
=> DFA-1520 new allowed domains

express/src/controllers/manage-account.ts, express/src/lib/lambda-facade/StubLambdaFacade.ts, express/src/routes/manage-account.ts
Add a rough and ready stubbed response for list services and list clients so sign in succeeds.
Delete a couple of logging calls that aren't needed.
=> BAU Add stub responses for successful sign in

express/src/views/create-account/get-email.njk
Remove margin from input on enter email page.
=> BAU Remove margin from input

express/src/views/sign-in-password.njk
Update the 'Enter your password' page
=> DFA-2028 Update the 'Enter your password' page

express/src/routes/testing-routes.ts, express/src/views/there-is-a-problem.njk
Create the 'problem with the service' page
=> DFA-2027 Create the 'problem with the service' page

express/src/routes/testing-routes.ts, express/src/views/forgot-password.njk
Create the 'forgot your password' page
=> DFA-2029 Create the 'forgot your password' page

.github/workflows/build-front.yml, .github/workflows/check-code-quality.yml, .github/workflows/check-pr.yml, .github/workflows/delete-deployment.yml, .github/workflows/deploy-branch.yml, .github/workflows/deploy-to-paas.yml, .github/workflows/run-acceptance-tests.yml, .github/workflows/run-unit-tests.yml, express/features/email-verification-resend.feature, express/features/mobile-verification-resend.feature, express/features/support/steps/email-verification-resend-steps.ts, express/features/support/steps/mobile-verification-resend-steps.ts, express/features/support/steps/shared-functions.ts, express/features/support/steps/shared-steps.ts, express/tsconfig.json
-  Add workflows to run unit and acceptance tests on PRs
- Fix acceptance tests 
Correctly await when the submit button is clicked. Hard-coded waits cause the function to time out. Await the `waitForNavigation` function instead.
=> DFA-2030: Run unit and acceptance tests on PRs

express/src/controllers/create-account.ts, express/src/middleware/emailValidator.ts, express/src/middleware/passwordValidator.ts, express/src/views/account/check-email.njk, express/src/views/create-account/check-email.njk, express/src/views/create-account/check-mobile.njk, express/src/views/dashboard/private-beta.njk, express/src/views/sign-in-otp-mobile.njk
Align the content in the build to the content doc [Sign in flow]
=> DFA-2015 Align the content in the build to the content doc

.github/workflows/deploy-branch.yml
Use the correct dependent job name
=> BAU: Fix deployment from a branch

express/src/routes/testing-routes.ts, express/src/views/create-new-password.njk
Create the 'Create a new password' page [FE -reset password]
=> DFA-2032 Create the 'Create a new password' page [FE -reset password]

README.md
Update README.md.  See README.md for changes.
=> BAU Update README.md

express/src/app.ts, express/src/controllers/create-account.ts, express/src/lib/cognito/StubCognitoClient.ts
Throw error in create account controller and add a stub return value so the route continues to work correctly when we add a 404 page.
=> DFA-2023: Stub create account flow

.gitignore, README.md, backend/dynamo-db/docker-compose.yml, backend/dynamo-db/template.yaml, express/.env.example, express/package.json, express/src/app.ts, express/src/lib/dynamodb/sessionStorage.ts, package-lock.json
- [npm: connect-dynamodb](https://www.npmjs.com/package/connect-dynamodb)  for session storage.
- The session table is created by a SAM Template
- The default in-memory implementation can be used if an env var is specified.
- A local implementation of DDB using docker-compose
=> DFA 2123 implement dynamodb session storage

backend/dynamo-api/src/client/DynamoClient.ts, backend/dynamo-api/src/handlers/get-user.ts, backend/dynamo-api/src/handlers/put-service-user.ts, express/@types/user.d.ts, express/src/app.ts, express/src/controllers/create-account.ts, express/src/controllers/manage-account.ts, express/src/controllers/sign-in.ts, express/src/lib/clientUtils.ts, express/src/lib/userUtils.ts, express/src/routes/manage-account.ts, express/src/routes/testing-routes.ts, express/src/services/cognito/CognitoClient.ts, express/src/services/cognito/CognitoInterface.ts, express/src/services/cognito/StubCognitoClient.ts, express/src/services/lambda-facade/LambdaFacade.ts, express/src/services/lambda-facade/LambdaFacadeInterface.ts, express/src/services/lambda-facade/StubLambdaFacade.ts, express/src/services/self-service-services-service.ts, express/src/views/add-service-name.njk
This is mostly getting rid of the user from the session and using CognitoId in URLs where we might have used the user stored in the session before.
=> DFA-2148 rationalise the session

express/src/controllers/sign-in.ts, express/src/middleware/authoriser.ts, express/src/routes/sign-in.ts, express/src/routes/testing-routes.ts, express/tests/middleware/authoriser.test.ts
Redirecting to /sign-in-again page if session has expired.
=> DFA-2014: Check if session has expired

.github/workflows/check-code-quality.yml, .github/workflows/delete-deployment.yml, .github/workflows/deploy-to-paas.yml, ci/apply-github-role.sh, ci/apply-sam-template.sh, ci/apply-sse-infrastructure.sh, ci/github-actions-role.yml, ci/sse-infrastructure.yml, express/Dockerfile, express/src/services/lambda-facade/StubLambdaFacade.ts
- Add frontend Dockerfile
- Add template for GHA role
- Add templatre for ECR repo
- Add scripts to apply the templates
- Use latest actions
=> DFA-2048: ECR repo template and SAM scripts

express/src/controllers/manage-account.ts, express/src/routes/manage-account.ts, express/src/routes/testing-routes.ts, express/src/views/account/change-service-name.njk, express/src/views/service-details/layout-service-details.njk
- Change service name and render client-details with success banner
=> DFA-1023-update-service-name

express/src/controllers/sign-in.ts, express/src/routes/sign-in.ts, express/src/routes/testing-routes.ts
- Update the sign-in flow to redirect to /no-account when account is not found with the provided details
=> DFA-1097- check user email flow - redirect to /no-account no user

express/features/sign-in.feature, express/features/support/steps/sign-in-steps.ts, express/src/services/cognito/StubCognitoClient.ts, express/stub/stubs-config.json
=> DFA-1097- no-account found scenario - acceptance test

express/src/routes/testing-routes.ts, express/src/views/wrong-otp-too-many-times.njk
User entered the wrong security code too many times - frontend only
=> DFA-2050 DFA-2054 User entered the wrong security code too many times

.github/workflows/deploy-to-paas.yml, .github/workflows/publish.yml, express/manifest.yml
Deploy a test instance on every merge to main.
_Successful run_
_https://github.com/alphagov/di-onboarding-self-service-experience/actions/runs/3478969374_
=> DFA-2270: Add Publish workflow

backend/cognito/src/handlers/password-reset-custom-message.ts, backend/cognito/template.yaml, backend/cognito/tsconfig.json, express/features/sign-in.feature, express/features/support/steps/sign-in-steps.ts, express/src/controllers/sign-in.ts, express/src/routes/sign-in.ts, express/src/routes/testing-routes.ts, express/src/services/cognito/CognitoClient.ts, express/src/services/cognito/CognitoInterface.ts, express/src/services/self-service-services-service.ts, express/src/views/forgot-password.njk, package-lock.json, package.json
- Custom message trigger for forgot password - Password reset flow.
- ES lint changes - added more safer type such as never, unknown in place of any - As suggested.
- Acceptance tests of the forgot password flow.
=> DFA 2037 send email code

express/assets/css/app.scss, express/assets/css/modules/_tick-cross.scss, express/assets/images/cross-grey.svg, express/assets/images/tick.svg, express/src/routes/testing-routes.ts, express/src/views/service-details/client-details.njk, express/src/views/service-details/layout-service-details.njk, express/src/views/service-details/team-members.njk
Create the front-end for 'Team members' page
=> DFA-2265 - Create 'Team members' page front-end

express/src/routes/testing-routes.ts, express/src/views/service-details/invite-team-member.njk
Create 'invite team member' page frontend
=> DFA-2285 - Create 'invite team member' page frontend

express/assets/css/modules/_show-password.scss, express/assets/javascripts/toggle-public-key-view.js, express/src/views/service-details/client-details.njk
Accessibility fix for show/hide public key
Accessibility fix for show/hide password
=> DFA-2342 Accessibility fixes

express/src/views/layout/base.njk
Update the links on the footer
=> SSE-2363 - Update the links on the footer

express/src/routes/testing-routes.ts, express/src/views/service-details/invitation-sent.njk, express/src/views/service-details/layout-service-details.njk
Create the 'Email invite sent' page front-end
=> DFA-2290 - Create the 'Email invite sent' page

express/src/views/service-details/change-public-key.njk
=> SSE-2362 - Update the Public Key page

express/src/views/service-details/client-details.njk
Show empty value for the public key field if the user has not updated it.
=> SSE-2372 Show empty value for the public key field

express/src/routes/testing-routes.ts, express/src/views/name-content-info.njk
Create the 'Add a name' page front-end
=> SSE-2284 - Create the 'Add a name' page

backend/cognito/src/handlers/password-reset-custom-message.ts, express/features/sign-in-unhappy-paths.feature, express/features/support/steps/shared-steps.ts, express/src/controllers/sign-in.ts, express/src/routes/sign-in.ts, express/src/routes/testing-routes.ts, express/src/services/cognito/CognitoClient.ts, express/src/services/cognito/CognitoInterface.ts, express/src/services/cognito/StubCognitoClient.ts, express/src/services/self-service-services-service.ts, express/src/views/create-new-password.njk
- Save reset password calling confirm forgot Password API
=> SSE- 2039 password reset flow confirm forgot password

express/src/routes/manage-account.ts, express/src/routes/testing-routes.ts, express/src/views/create-account/resend-email-code.njk, express/src/views/create-account/resend-phone-code.njk, express/src/views/resend-phone-code-sign-in.njk
Remove the 'back' link on the 'Resend security code' page
=> SSE-2384 - Remove the 'back' link on the 'Resend security code' page

express/assets/css/app.scss, express/src/controllers/manage-account.ts, express/src/views/service-details/client-details.njk
Render code text in a code element on client details page
=> SSE-2377 - Render code text in a code element on client details page

backend/cognito/src/handlers/password-reset-custom-message.ts, backend/cognito/template.yaml, backend/dynamo-api/src/handlers/send-private-beta-notification.ts, express/assets/css/modules/_header.scss, express/src/views/components/cookie-banner.njk, express/src/views/finish-connecting-sign-in-journey.njk, express/src/views/index.njk, express/src/views/layout/base.njk, express/src/views/macros/breadcrumbs.njk, express/src/views/service-details/client-details.njk, express/src/views/service-details/private-beta.njk, express/src/views/sign-in.njk
Update the product name to 'GOV.UK One Login'
=> SSE-2329 - Update the product name to 'GOV.UK One Login'

express/src/routes/testing-routes.ts, express/src/views/service-unavailable.njk
Build 'service unavailable' page - frontend
=> SSE-2376 - Build 'service unavailable' page

express/features/support/steps/client-steps.ts, express/features/support/steps/shared-functions.ts, express/features/support/steps/shared-steps.ts, express/features/update-client.feature, express/src/controllers/manage-account.ts, express/src/lib/publicKeyUtils.ts, express/src/routes/testing-routes.ts, express/src/services/lambda-facade/StubLambdaFacade.ts
Use correct client ID
Use public key prepared for Auth Client Registry
=> SSE-2385 public key data

backend/domains/production/template.yaml
Add CloudFormation template to create hosted zone and replicate records currently found in Auth's account.
=> DFA-2310 Take ownership of sign-in.service.gov.uk

express/src/controllers/manage-account.ts, express/src/middleware/validators/emailOtpValidator.ts, express/src/middleware/validators/mobileOtpValidator.ts, express/src/views/layout/base.njk, express/src/views/macros/form-inputs.njk, express/src/views/service-details/client-details.njk, express/src/views/service-details/layout-service-details.njk
Fix Medium accessibility issues
- remove spaces from security codes
- add "Error: " to pages with error messages
- update macro for Security code input
- update redirect urls output on Client details page
=> SSE-2379 - Fix Medium accessibility issues

README.md, backend/cognito/src/handlers/confirm-forgot-password-message.ts, backend/cognito/template.yaml, express/features/sign-in-unhappy-paths.feature, express/src/controllers/sign-in.ts, express/src/services/cognito/CognitoClient.ts, package.json
- Updating the account details with the password change time.
- A post forgot password confirmation lambda trigger that sends an email using SES
- Domain verification that is needed for SES email sending.
- In sandbox environment receipient also need to be added into the verified email identities.
=> SSE-2040-update-password-details-on-your-account

express/features/joining-private-beta.feature, express/features/support/steps/shared-steps.ts, express/features/support/test-setup.ts
Create Private beta acceptance tests as per AC in the story.
=> SSE-2336 - Create Private beta acceptance tests

backend/domains/development/template.yaml, backend/domains/integration/template.yaml, backend/domains/production/template.yaml, backend/domains/staging/template.yaml
Add integration hosted zone.
Add a condition to ensure idiots can't apply the wrong template in the wrong account and knock sites off the internet.
(I was the idiot btw).
=> SSE-2311 Add integration hosted zone and conditions

express/src/controllers/manage-account.ts
- serviceName not available in the private joining beta page. Updated the session to have the serviceName available so it can be displayed
=> SSE-2382 - Service name not visible in private beta join page

express/features/update-service-name.feature
Create Acceptance test for 'Change your service name' page
=> SSE-2475 - Create Acceptance test for 'Change your service name' page

express/src/routes/testing-routes.ts, express/src/views/create-account/choose-security-codes.njk, express/src/views/macros/form-inputs.njk
Create 'Choose how to get your security code' page frontend
=> Create 'Choose how to get your security code' page frontend

express/package.json, package-lock.json
SSE-2486 - Upgrade to govuk-frontend v4.5.0
=> SSE-2486 - Upgrade to govuk-frontend v4.5.0

infrastructure/ci/dev-platform/build/README.md, infrastructure/ci/dev-platform/build/create-aws-signer.sh, infrastructure/ci/dev-platform/build/create-container-signer.sh, infrastructure/ci/dev-platform/build/create-github-provider.sh, infrastructure/ci/dev-platform/build/secrets-for-gha.sh
Put commands used to create supporting stacks into shell scripts.
Create basic script to print the values needed for GHA Secrets.
=> SSE-2533 Supporting stacks for build account

infrastructure/ci/dev-platform/build/create-infrastructure-audit-hook.sh, infrastructure/ci/dev-platform/build/create-lambda-audit-hook.sh, infrastructure/ci/dev-platform/shared/create-infrastructure-audit-hook.sh, infrastructure/ci/dev-platform/shared/create-lambda-audit-hook.sh
Write shared scripts to create lamdba and infrastructure provencence check hooks.
Write scripts to invoke shared scripts for build account.
=> SSE-2511 Lambda and Infrastructure hooks in build account

infrastructure/ci/dev-platform/build/create-infrastructure-audit-hook.sh, infrastructure/ci/dev-platform/build/create-lambda-audit-hook.sh, infrastructure/ci/dev-platform/shared/create-infrastructure-audit-hook.sh, infrastructure/ci/dev-platform/shared/create-lambda-audit-hook.sh, infrastructure/ci/dev-platform/staging/create-infrastructure-audit-hook.sh, infrastructure/ci/dev-platform/staging/create-lambda-audit-hook.sh
Apply shared scripts from SSE-2511 to staging
=> SSE-2512 audit checks in staging

infrastructure/ci/dev-platform/build/create-infrastructure-audit-hook.sh, infrastructure/ci/dev-platform/build/create-lambda-audit-hook.sh, infrastructure/ci/dev-platform/integration/create-infrastructure-audit-hook.sh, infrastructure/ci/dev-platform/integration/create-lambda-audit-hook.sh, infrastructure/ci/dev-platform/shared/create-infrastructure-audit-hook.sh, infrastructure/ci/dev-platform/shared/create-lambda-audit-hook.sh
Call scripts from SSE-2511 for integration environment
=> SSE-2513 audit checks in integration

.github/workflows/check-pr.yml, .github/workflows/clean-up-deployments.yml, .github/workflows/delete-deployment.yml, .github/workflows/deploy-to-paas.yml, .github/workflows/publish.yml
Keep the cleanup functionality in a separate workflow so it can be set to send notifications separately
=> SSE-2520: Split the delete deployment workflow into two

infrastructure/ci/dev-platform/development/create-grafana-key-rotator.sh, infrastructure/ci/dev-platform/shared/create-grafana-key-rotator.sh
Fix bug in script that meant it would run without a name for the secret being specified.
=> SSE-2515 Grafana stacks in development

backend/cognito/src/handlers/confirm-forgot-password-message.ts
Update GOV.UK banner in password reset email
=> SSE-2564 - Update GOV.UK banner in password reset email

.github/workflows/deploy-dynamo-db.yml
Github Action to push dynamo db stack to build account.
=> SSE-2453 Upload DynamoDB to build account

infrastructure/ci/dev-platform/build/create-api-gateway-logging-stack.sh, infrastructure/ci/dev-platform/development/create-api-gateway-logging-stack.sh, infrastructure/ci/dev-platform/integration/create-api-gateway-logging-stack.sh, infrastructure/ci/dev-platform/production/create-api-gateway-logging-stack.sh, infrastructure/ci/dev-platform/shared/create-api-gateway-logging-stack.sh, infrastructure/ci/dev-platform/staging/create-api-gateway-logging-stack.sh
Add scripts used to create the api gateway logging stacks to the repo.
The script has not been run on development as a differently named stack already exists.
=> SSE-2576 API Gateway logging stacks

infrastructure/ci/dev-platform/build/create-grafana-key-rotator.sh, infrastructure/ci/dev-platform/build/create-grafana-metrics.sh, infrastructure/ci/dev-platform/development/create-aws-signer.sh, infrastructure/ci/dev-platform/development/create-container-signer.sh, infrastructure/ci/dev-platform/development/create-github-provider.sh, infrastructure/ci/dev-platform/development/create-infrastructure-audit-hook.sh, infrastructure/ci/dev-platform/development/create-lambda-audit-hook.sh, infrastructure/ci/dev-platform/development/deploy-deployment-pipeline-stack.sh
- script for deployment for development
- script for deployment for build
=> SSE-2519-add deployment script for build and development env

infrastructure/ci/dev-platform/staging/create-slack-stack.sh, infrastructure/ci/dev-platform/staging/create-vpc-stack.sh
- add staging create vpc stack script
- add staging create slack stack script
=> SSE-2519-add-staging-pipeline-script

infrastructure/ci/dev-platform/staging/create-grafana-key-rotator.sh, infrastructure/ci/dev-platform/staging/create-grafana-metrics.sh
- add staging create grafana key rotator script
- add staging create grafana metrics script
=> SSE-2519 add slack notify script

express/src/controllers/clients.ts, express/src/routes/clients.ts, express/src/routes/testing.ts, express/src/services/lambda-facade/StubLambdaFacade.ts, package-lock.json
Move routes used in the main app for One Login Admin out of the testing routes
=> SSE-2559 - Move routes used in the main app for One Login Admin out of testing routes

express/src/routes/sign-in.ts, express/src/routes/testing.ts, express/src/views/confirm-phone-number.njk, express/src/views/new-phone-number.njk, express/src/views/resend-phone-code-sign-in.njk, package-lock.json
Fix bugs with routes for resend phone code and new phone number functionality during login
=> Fix bugs with routes for resend phone code and new phone number functionality during login

express/tests/lib/allowed-email-domains.test.ts, express/tests/lib/mobileNumberUtils.test.ts, express/tests/lib/publicKeyUtils.test.ts, express/tests/lib/validators/checkOtp.test.ts, express/tests/middleware/convertPublicKeyForAuth.test.ts, express/tests/middleware/validators/mobileValidator.test.ts
Add test cases for validating allowed email domains
Add more test cases for validating public keys
Use jest mocking API to mock files on disk when reading resources
Organise some test into sections using `describe`
=> BAU: Add some missing unit tests and cases for library utils

.github/workflows/upload-frontend-secure-pipelines.yml
-  update workflow to use dev platform worked
- test the workflow and frontend template
=> SSE-2605 - update frontend deploy workflow

backend/cognito/create-email-identity.sh, backend/cognito/email-identity-template.yml, backend/cognito/template.yml, infrastructure/domains/sse-domains.yml
Separate creation of email identity into different stack with script to deploy it and check whether id gets verified.
=> SSE-2622 Split out email identity creation

.github/workflows/upload-api-secure-pipelines.yml
Use caching and split the workflow into stages
=> SSE-2534: Update API secure pipelines workflow

.github/workflows/upload-frontend-secure-pipelines.yml, infrastructure/api/sse-api.yml
- Add logs:PutResourcePolicy permission for step functions
- Use correct ECR action version
=> SSE-2590: Fix API and Frontend deployment issues

acceptance-tests/features/joining-private-beta.feature, acceptance-tests/features/sign-in-unhappy-paths.feature, acceptance-tests/features/update-client.feature, acceptance-tests/features/update-service-name.feature, acceptance-tests/features/your-account.feature, acceptance-tests/support/steps/shared-functions.ts, acceptance-tests/support/steps/shared-steps.ts, express/src/controllers/services.ts, express/src/views/account/account.njk, express/src/views/layouts/account.njk, express/src/views/services/services.njk
Add side navigation to account and service pages
=> SSE-2606 - Add side nav to account and service pages

infrastructure/ci/dev-platform/shared/create-vpc-stack.sh
fix vpc stack script, add missing param for ECR
=> SSE-2567: Update create-vpc-stack.sh

acceptance-tests/features/your-account.feature, backend/api/src/dynamodb-client.ts, express/src/app.ts, express/src/controllers/account.ts, express/src/controllers/clients.ts, express/src/controllers/register.ts, express/src/controllers/services.ts, express/src/controllers/session.ts, express/src/controllers/sign-in.ts, express/src/middleware/authoriser.ts, express/src/middleware/errors.ts, express/src/middleware/request-handler.ts, express/src/middleware/sign-in-status.ts, express/src/middleware/validators/password-validator.ts, express/src/routes/account.ts, express/src/routes/base.ts, express/src/routes/clients.ts, express/src/routes/sign-in.ts, express/tests/middleware/validators/common-password-validator.test.ts
**Add utility middleware to create request handlers**
- Introduce simple utility methods to streamline the creation of middleware functions
- Use the functions to define the type of the handlers for better type checking
- Use the utility functions in the middleware library
- Add a utility function to create a middleware function to render a view
Use the function in routes
**Tidy up controllers**
- Use nonNull instead of type assertion (`as <type>`) to ensure values are actually present at run-time
- Try-catch exceptions around methods that throw them
- Use `RequestHandler` type for controller middleware functions
- Use arrow functions so the function type can be specified
- Use the render helper function
- Return `res.render` and `res.redirect`
- Remove unnecessary `async`
---
- Use the …
=> BAU: Tidy up controllers

express/src/controllers/clients.ts, express/src/views/clients/change-user-attributes.njk, express/src/views/clients/client-details.njk, express/src/views/macros/form-inputs.njk
=> SSE-2620 - Update User Attributes Format

.github/workflows/upload-frontend-secure-pipeline.yml
- Validate the template before uploading
- Check if the docker image exists in ECR before uploading the frontend package
=> SSE-2626: Add checks to frontend secure pipelines workflow

.github/workflows/check-pr.yml, .github/workflows/deploy-branch.yml, .github/workflows/deploy-to-paas.yml, .github/workflows/publish.yml, express/assets/css/app.scss, express/manifest.yml, express/src/app.ts, express/src/config/environment.ts, express/src/views/layouts/base.njk
Implement a banner for non-production environments
=> SSE-2595 Implement a banner for non-production environments

acceptance-tests/features/email-verification-resend.feature, acceptance-tests/features/mobile-verification-resend.feature, express/src/views/common/resend-security-code.njk, express/src/views/layouts/base.njk
=> SSE-2607 - Update links

express/src/controllers/sign-in.ts, express/src/routes/sign-in.ts, express/src/views/common/resend-security-code.njk, express/src/views/sign-in/enter-password.njk, express/src/views/sign-in/resend-text-code.njk, express/src/views/sign-in/resend-text-code/enter-password.njk
Prompt for password to resend SMS code during sign-in
=> SSE-2609 - Prompt for password to resend SMS code during sign-in

infrastructure/aws.sh, infrastructure/ci/secure-pipelines/configure-github-repo.sh, infrastructure/ci/secure-pipelines/deploy-pipelines.sh, infrastructure/ci/secure-pipelines/deploy-support-stacks.sh, infrastructure/ci/secure-pipelines/deployment-pipelines.template.yml, infrastructure/ci/secure-pipelines/github-subject-claim-template.json
**Automatically write the correct values from stack outputs to GitHub Actions for secure pipelines deployments**
- Create a new GitHub Actions environment if it doesn't exist
- Write variables to be used by GitHub Actions workflows, based on the stack outputs
- Add GitHub Actions outputs to the pipelines stack
=> SSE-2685: Automatically configure GitHub Actions deployment variables for secure pipelines

infrastructure/api/sse-api.yml
- add Kms Key Arn  in auth lambda
- add Kms Key for auth api key
- add Auth Kms Key Alias
=> SSE-2636: Store and retrieve the Auth API key securely

infrastructure/api/sse-api.yml
=> SSE-2636 - Set KeyUsage

express/resources/allowed-test-domains.txt, express/src/config/environment.ts, express/src/lib/validators/allowed-email-domains.ts, package-lock.json
Add the domain to allowed test domain
Add more filters and checks to the function reading and parsing the file
=> SSE-2754: Allow pen tester email domain

backend/cognito/cognito.template.yml, infrastructure/frontend/frontend.template.yml
- Add CloudFront config with caching and access logging
- Add session secret value to frontend environment
- Ensure access logs buckets are globally unique by appending an ID
- Output frontend URL
=> SSE-2740: Add a CloudFront distribution to the frontend template

.github/workflows/run-acceptance-tests.yml, acceptance-tests/features/clients/change-post-logout-redirect-uris.feature, acceptance-tests/features/clients/change-public-key.feature, acceptance-tests/features/clients/change-redirect-uris.feature, acceptance-tests/features/clients/change-user-attributes.feature, acceptance-tests/features/clients/client-details.feature, acceptance-tests/support/steps/clients-steps.ts, acceptance-tests/support/steps/input-steps.ts, acceptance-tests/support/steps/public-key-steps.ts, express/src/views/clients/client-details.njk
Create Client details flow acceptance tests
=> SSE-2335 - Create Client details flow acceptance tests

infrastructure/ci/secure-pipelines/deployment-support.template.yml
Deployed to Development only (Karl will implement all Accounts).
=> SSE-2678:Added Checkov Hook to Infrastructure Template.

acceptance-tests/features/clients/client-details.feature, acceptance-tests/features/services/joining-private-beta.feature
Remove functional tests which depend on external resources
=> BAU - Remove functional tests which depend on external resources

.github/workflows/build-frontend-image.yml, .github/workflows/deploy-branch.yml, .github/workflows/deploy-component.yml, infrastructure/ci/development/deployment-config.template.yml, infrastructure/config/network.template.yml, infrastructure/frontend/frontend.template.yml
**Update dev deployment workflow**
Update the workflow for the latest changes in frontned components (public ALB and a DNS record with a custom domain)
Set correct parameters and values
Update permissions for the GitHub Actions dev role
**Move ELB access logs bucket to the network config template**
Use one bucket for all ALB logs
This makes deleting frontend stacks easier as the bucket doesn't need to be emptied and deleted
=> SSE-2521: Deploy admin tool frontend from GitHub Actions to dev

express/src/views/macros/form-inputs.njk
Text for change of redirect urls corrected per SSE-2814.
=> Correct redirect urls text.

express/assets/javascripts/prevent-multiple-form-submission.js, express/src/views/layouts/base.njk, express/src/views/layouts/form.njk
Prevent frontend to submit form multiple times
=> SSE-2839 Prevent frontend to submit form multiple times

backend/cognito/cognito.template.yml, express/src/controllers/register.ts, express/src/lib/utils/signup-status.ts, express/src/middleware/authoriser.ts, express/src/routes/register.ts, express/src/services/cognito/CognitoClient.ts, express/src/services/cognito/CognitoInterface.ts, express/src/services/cognito/StubCognitoClient.ts, express/src/services/self-service-services-service.ts, express/src/views/common/resume-after-password.njk, express/src/views/common/resume-from-password.njk, express/src/views/register/resend-email-code.njk, express/src/views/register/resume-after-password.njk, express/src/views/register/resume-from-password.njk, express/tests/lib/utils/signup-status.test.ts, express/tests/middleware/authoriser.test.ts, infrastructure/frontend/frontend.template.yml, package-lock.json, package.json
I think the commits have my name against them ... only because I squashed them
All the hard work was David Stump's
=> SSE-2781 Squashed

express/src/app.ts, express/src/config/helmet.ts, package-lock.json, package.json
SSE-2796 Implement OWASP recommended HTTP response headers using helmet, controlled by a configuration file.
=>  SSE-2796 - Implement OWASP recommended HTTP response headers

.github/workflows/release-prod.yml
- add workflow for deploying into build env
=> add release workflow

backend/api/api.template.yml, backend/api/src/handlers/notifications/send-public-beta-notification.ts, express/src/controllers/clients.ts, express/src/routes/clients.ts, express/src/services/lambda-facade/LambdaFacade.ts, express/src/services/lambda-facade/LambdaFacadeInterface.ts, express/src/services/lambda-facade/StubLambdaFacade.ts, express/src/services/self-service-services-service.ts, infrastructure/config/network.template.yml
Rename Private beta variables to Public beta
=> SSE-2785 Rename Private beta variables to Public beta

express/package.json, package-lock.json
Vulnerabilities update for node modules
=> Vulnerabilities update for node modules

backend/api/src/handlers/step-functions/new-client.ts, backend/api/src/handlers/step-functions/new-service.ts, backend/api/src/handlers/step-functions/update-client.ts
SSE-2532 - recognise, log and pass on errors returned by AWS Step Functions
=> SSE-2532 - handle step function errors

express/src/controllers/sign-in.ts
Remove port from non localhost urls for password reset on log in link generation
=> SSE-2803 - Remove port from non localhost urls for password reset

express/src/middleware/sign-in-middleware.ts, express/src/services/cognito/CognitoClient.ts, infrastructure/frontend/frontend.template.yml
New Release of SSE-2798 (with Permissions)
=> SSE-2798:Able to login with expired 6-digit Security Code

acceptance-tests/features/register.feature, acceptance-tests/features/services/joining-public-beta.feature, backend/cognito/src/handlers/send-password-changed-email.ts, express/src/views/404.njk, express/src/views/clients/public-beta-form-submitted.njk, express/src/views/common/resend-security-code.njk, express/src/views/index.njk, express/src/views/layouts/base.njk, express/src/views/register/account-exists.njk, express/src/views/register/enter-email-address.njk, express/src/views/test/enter-app-code.njk, express/src/views/test/finish-connecting-sign-in-journey.njk, express/src/views/test/service-unavailable.njk, express/src/views/test/set-up-auth-app.njk, express/src/views/there-is-a-problem.njk
Update contact links to work with new zendesk functionality
=> SSE-2828 - Update contact links to work with new zendesk functionality

express/src/views/clients/public-beta-form-submitted.njk
=> Update slack url

infrastructure/ci/development/deployment-config.template.yml
…. Deploys on aws, did not check preview deployment.
=> SSE-2913 - GitHubActionsRole policies refactor

backend/cognito/src/handlers/create-password-reset-message.ts, express/src/controllers/sign-in.ts, express/src/services/cognito/CognitoClient.ts, express/src/services/cognito/CognitoInterface.ts, express/src/services/self-service-services-service.ts
…hough as there is an issue that Martin is working on.
=> SSE-2877 Add WAF to Cognito

backend/cognito/cognito.template.yml, backend/cognito/src/handlers/create-password-reset-message.ts, backend/cognito/src/handlers/send-password-changed-email.ts
Change logo link in admin tool related emails
=> SSE-2584 Change logo link in admin tool related emails

backend/api/api.template.yml
=> SSE-2777: log data protection

backend/cognito/src/handlers/send-password-changed-email.ts
SSE-2874 - disable functionality of password reset confirmation email lambda
=> SSE-2874 - password reset confirmation email bugfix

infrastructure/ci/configure-deployment-parameters.sh, infrastructure/ci/secure-pipelines/deployment-pipelines.template.yml, infrastructure/frontend/frontend.template.yml
- add env ALLOWED_EMAIL_DOMAINS_SOURCE
- updated the deployment script for email domain param
-
=> Sse 2947 updated email domains

express/resources/allowed-email-domains.txt, express/src/views/register/enter-email-address.njk
Update allowed email domains list for production
=> SSE-2949 Update allowed email domains list for production

express/src/middleware/errors.ts
SSE-2956 improve robustness of error handling where a session may not exist or the remote logging service is unavailable
=> SSE-2956 improve robustness of error handling

infrastructure/config/network.template.yml
- add allow domains
- add allow rules
- access to google api
=> SSE-2750 add allow rules for google apis

infrastructure/ci/configure-deployment-parameters.sh, infrastructure/ci/development/deployment-config.template.yml, infrastructure/dev/deploy.sh
SSE-2750 - configuration for google authentication secret.
=> SSE-2750 - configuration for google authentication secret.

express/src/controllers/services.ts, express/src/middleware/validators/service-name-validator.ts, express/src/routes/register.ts, express/src/routes/services.ts, express/src/views/services/add-new-service.njk, express/src/views/services/services.njk
Add multi service functionality frontend
=> SSE-2997 - Add multi service functionality frontend

.gitignore, README.md, express/.env.example, express/src/controllers/register.ts, express/src/lib/sheets/SheetsService.ts, express/src/lib/sheets/index.ts, express/src/lib/sheets/interface.ts, express/src/lib/sheets/realSheets/realSheetsService.ts, express/src/lib/sheets/stubSheets/stubSheetsService.ts, express/src/routes/register.ts, express/src/routes/services.ts, express/src/services/self-service-services-service.ts, infrastructure/ci/configure-deployment-parameters.sh, infrastructure/ci/development/deployment-config.template.yml, infrastructure/dev/deploy.sh, infrastructure/frontend/frontend.template.yml, package-lock.json, package.json
SSE-2750 - new user reporting to a Google Sheet
=> SSE-2750 - new user reporting

infrastructure/ci/development/deployment-config.template.yml
- add GHA role permissions
- SSE-2991
=> SSE-2991 add product pages permissions

infrastructure/config/domain.template.yml
- update dns record to remove paas record
- SSE-2824 removal of paas
=> remove paas dns record

acceptance-tests/features/clients/client-details.feature, infrastructure/config/domain.template.yml
Added the domain delegation for docs.sign-in.service.gov.uk to nameservers in the account `di-documentation #203073707786 `
=> Bau migrate docs from paas

infrastructure/ci/secure-pipelines/deployment-support.template.yml
Update Team Manual location following migration
=> Update Team Manual location

acceptance-tests/features/sign-in.feature
[SSE-3076](https://govukverify.atlassian.net/browse/SSE-3076)
- Added 3 tests related to backlink 
- updated few steps with correct step prefix(Given/When/Then)
[SSE-3076]: https://govukverify.atlassian.net/browse/SSE-3076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SSE-3076 Added few tests related to back link

express/src/lib/sheets/realSheets/realSheetsService.ts
Remove logging form google sheet service
=> SSE-3088 - Remove logging form google sheet service

acceptance-tests/features/register.feature, acceptance-tests/support/steps/shared-steps.ts, express/resources/allowed-test-domains.txt
Added the missing tests related to registration journey
=> SSE-3074 : Added tests related to register journey

acceptance-tests/features/account.feature
Added missing tests related to Your Account 
https://govukverify.atlassian.net/browse/SSE-3077
=> SSE-3077 your account acceptance tests

backend/api/api.template.yml, backend/cognito/cognito.template.yml
- add lambda layer for dynatrace
- Dynatrace integration
=> SSE-3038 Dynatrace Integration

acceptance-tests/features/clients/change-post-logout-redirect-uris.feature, acceptance-tests/features/clients/change-public-key.feature, acceptance-tests/features/clients/change-user-attributes.feature, acceptance-tests/features/clients/client-details.feature, acceptance-tests/features/services/joining-public-beta.feature, acceptance-tests/support/steps/input-steps.ts
Added tests in the following feature files 
- change-post-logout-redirect-uris.feature
- change-public-key.feature
- change-redirect-uris.feature
- change-user-attributes.feature
- client-details.feature
- joining-public-beta.feature
=> SSE-3078_ client details and public beta tests

backend/api/api.template.yml, backend/cognito/cognito.template.yml
- enabled dynatrace for API & Cognito lambda
- SSE-3038
=> SSE-3038 enabled lambd adynatrace

.github/actions/check-pii-audit/action.yml, .github/workflows/check-code-quality.yml, infrastructure/config/pii_scan_ignore.txt, infrastructure/dev/pii_scan.sh, package.json
A new Utility to check for PII Filters being applied to Template Files where Logging actioned.
=> SSE-2994:Created PII Scanner Script which run as part of Code Quality Checks and also available as Command Line Option

acceptance-tests/features/clients/change-public-key.feature, acceptance-tests/features/clients/client-details.feature, express/src/views/clients/change-public-key.njk, express/src/views/clients/client-details.njk, express/src/views/test/change-public-key-v2.njk
SSE-3080 - Replace all old PaaS links
=> SSE-3080 - Replace all old PaaS links

acceptance-tests/features/account.feature, acceptance-tests/features/clients/change-post-logout-redirect-uris.feature, acceptance-tests/features/clients/change-public-key.feature, acceptance-tests/features/clients/change-redirect-uris.feature, acceptance-tests/features/clients/change-user-attributes.feature, acceptance-tests/features/clients/client-details.feature, acceptance-tests/features/register.feature, acceptance-tests/features/services/joining-public-beta.feature, acceptance-tests/features/services/update-service-name.feature, acceptance-tests/features/sign-in.feature, acceptance-tests/package.json, acceptance-tests/support/steps/shared-steps.ts, package-lock.json
- Accessibility tests are implemented for all admin tool pages
- All tests are categorised using @accessible tag
- Updated package.json to run only accessible tests as and when required
- All accessible tests will run in every build along with other acceptance tests
- List of tests are [here](https://docs.google.com/spreadsheets/d/10cZJ_KwaXsNBpeFYlu_UtRO7mRg8bMLOcQPyhda5asc/edit#gid=1265369522rl)
=> SSE-3081 Accessible Tests for admin tool (Refactored)

.github/workflows/deploy-branch.yml
- N/A
- Existing GH action for `.github/workflows/deploy-branch.yml` to add paths to template files
- N/A
=> [FIX]- adds template path to action

infrastructure/ci/configure-deployment-parameters.sh
SSE-3232 Add a new parameter in the environment for identity-verification-enabled
=> SSE-3232 Add a new parameter in the environment for id verification

backend/api/api.template.yml, infrastructure/ci/configure-deployment-parameters.sh
- add auth api key and url params
- updated AUTH_REGISTRATION_BASE_URL with ssm value
- Admin Tool: Migrate Environments below Integration to use Auth Staging API
=> SSE-3248 Auth API

infrastructure/dev/pii_scan.sh, package-lock.json, package.json
These are minor amendments and enhancements to [SSE-2994](https://govukverify.atlassian.net/browse/SSE-2994) work which was identified during a Demonstration of said ticket in Sprint Review.
[SSE-2994]: https://govukverify.atlassian.net/browse/SSE-2994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SSE:3176 - Maintenance Fixes identified during Demo for SSE-2994

.github/workflows/run-acceptance-tests.yml, package-lock.json, ui-automation-tests/acceptance-features/services/add-service.feature, ui-automation-tests/package.json
https://govukverify.atlassian.net/browse/SSE-3266
=> SSE-3266: Added test for add a service 

infrastructure/ci/development/deployment-config.template.yml
- update the template for GHA role permission for dev env
- incorrect condition
=> SSE-3278 - dev only GHA role permissions

.gitignore, express/assets/css/app.scss, express/assets/javascripts/toggle-public-key-view.js, express/src/controllers/clients.ts, express/src/lib/updateContacts.ts, express/src/routes/clients.ts, express/src/services/lambda-facade/StubLambdaFacade.ts, express/src/views/clients/change-service-name.njk, express/src/views/clients/client-details.njk, express/src/views/clients/confirm-contact-removal.njk, express/src/views/clients/enter-contact-email.njk, express/src/views/clients/enter-contact.njk, express/src/views/layouts/base.njk, express/src/views/layouts/client.njk, express/src/views/macros/form-inputs.njk, express/tests/lib/updateContacts.test.ts, ui-automation-tests/acceptance-features/clients/change-contacts.feature, ui-automation-tests/acceptance-features/services/update-service-name.feature, ui-automation-tests/support/steps/shared-steps.ts
Update 'Service details' Section
=> SSE-3226 Update 'Service details' Section

express/src/controllers/clients.ts, express/src/lib/updateContacts.ts, express/tests/lib/updateContacts.test.ts
Add validation for Contact confirmation removal page
=> SSE-3226 Add validation for Contact confirmation removal page

express/src/views/services/services.njk
SSE-3314 - enable multi-service feature
=> SSE-3314 - enable multi-service feature

express/tests/constants.ts, express/tests/controllers/register.test.ts, express/tests/controllers/services.test.ts, express/tests/controllers/session.test.ts
> [!NOTE]  
> This PR makes no production code changes and adds only unit tests
- Unit tests where they are missing for the `session.ts`, `services.ts` and `register.ts` controllers
- Added some additional tests constants 
- N/A
=> BAU: More controller tests

express/src/routes/services.ts
> [!WARNING]
-   [ ] tests have been written to cover any new or updated functionality
-   [ ] new configuration parameters have been deployed to all environments, see [configuration management](https://govukverify.atlassian.net/l/cp/N7q3Vh3r).
- …
=> SSE-3361 - remove route toggle for Add new service page for Admin Tool

express/resources/allowed-email-domains.txt
> [!WARNING]
-   [ ] tests have been written to cover any new or updated functionality
-   [ ] new configuration parameters have been deployed to all environments, see [configuration management](https://govukverify.atlassian.net/l/cp/N7q3Vh3r).
- …
=> SSE-3328 - enable gov.wales domain

express/tests/constants.ts, express/tests/services/lambda-facade/LambdaFacade.test.ts, express/tests/services/self-service-services-service.test.ts
=> FIX: Updates Unit tests

.github/workflows/test-application.yml
=> SSE-3414 gha worflow fix

express/tests/config/helmet.test.ts, express/tests/constants.ts, express/tests/controllers/clients.test.ts, express/tests/middleware/validators/service-name-validator.test.ts
=> BAU: Add Unit tests

express/src/lib/public-key.ts, express/src/middleware/convert-public-key.ts, express/tests/lib/public-key.test.ts
=> SSE-3332:Added additional Validation for Public Key to ensure Auth compatability

express/src/middleware/convert-public-key.ts, express/tests/middleware/convert-public-key.test.ts
=> SSE-2815: Fix error message when clicking cancel after entering an invalid public key

.github/dependabot.yml, .github/workflows/build-frontend-image.yml
=> Dependabot: Disabled docker login and grouped updates.

express/@types/client.d.ts, express/src/controllers/clients.ts, express/tests/controllers/clients.test.ts
=> SSE-3448: Fix undefined claims

README.md, backend/api/src/handlers/dynamodb/put-service-client.ts, express/@types/client.d.ts, express/src/controllers/clients.ts, express/src/routes/clients.ts, express/src/services/lambda-facade/StubLambdaFacade.ts, express/src/views/clients/change-id-token-algorithm.njk, express/src/views/clients/client-details.njk, express/tests/constants.ts, express/tests/controllers/clients.test.ts, express/tests/services/lambda-facade/StubLambdaFacade.test.ts, ui-automation-tests/acceptance-features/clients/change-id-signing-token-algorithm.feature, ui-automation-tests/support/steps/clients-steps.ts, ui-automation-tests/support/steps/shared-steps.ts
> [!WARNING]
-   [x ] this pull request meets the acceptance criteria of the ticket …
=> SSE-3413 Frontend implementation for "Advanced Options"

express/src/views/clients/change-claims.njk, express/src/views/clients/client-details.njk, ui-automation-tests/acceptance-features/clients/change-claims.feature, ui-automation-tests/acceptance-features/clients/change-identity-verification.feature, ui-automation-tests/support/steps/clients-steps.ts
=> SSE-3450 Correct claim names

backend/api/src/handlers/auth/update-client.ts, backend/api/tests/handlers/auth/update-client.test.ts, express/src/controllers/clients.ts, express/tests/controllers/clients.test.ts
=> SSE-3462: Fix Backchannel Logout URI

backend/api/src/dynamodb-client.ts, backend/api/tests/dynamodb-client.test.ts, express/src/controllers/clients.ts, express/tests/constants.ts, express/tests/controllers/clients.test.ts
=> SSE-3465 clientLoCs defect

express/src/routes/clients.ts, ui-automation-tests/acceptance-features/clients/change-sector-identifier-uri.feature
=> SSE-3464 Sector identifier URI fix

backend/api/tests/contract-tests/tests/testClientRegistryContract.spec.ts
=> BAU: Fix Contract Test For Node 20

express/resources/allowed-email-domains.txt, express/src/views/register/enter-email-address.njk
=> ATO-926: allow slc email

backend/api/api.template.yml, backend/api/package.json, express/package.json, package-lock.json, package.json
We do not pin cfn version, which mean new rules are included whenever cfn-lint publishes
> [!WARNING]
-   any replaced …
=> BAU: update cfn ignore for new rule

express/src/views/clients/client-details.njk
> [!WARNING]
-   [X] this pull request meets the acceptance criteria of the ticket
-   [X] this branch is up-to-date with the main branch
-   [X] these changes are backwards compatible (no breaking changes) …
=> BAU: Fix content to refer to go-live page

package-lock.json
=> Fixes vunerability in application

express/resources/allowed-email-domains.txt, express/src/views/register/enter-email-address.njk
-   [ X] this pull request meets the acceptance criteria of the ticket
-   [ X] this branch is up-to-date with the main branch
-   [X ] these changes are backwards compatible (no breaking changes)
-   [NA ] tests have been written to cover any new or updated functionality
-   [NA ] new configuration parameters have been deployed to all environments, see [configuration management](https://govukverify.atlassian.net/l/cp/N7q3Vh3r).
-   [ NA] all external infrastructure dependencies have been updated in all environments
Added .nhs.uk to email domain list
=> Added .nhs.uk email domain

express/src/lib/validators/uri-validator.ts, express/tests/lib/validators/uris-validator.test.ts, express/tests/middleware/validators/uris-validator.test.ts, ui-automation-tests/acceptance-features/clients/change-backchannel-logout-uri.feature, ui-automation-tests/acceptance-features/clients/change-post-logout-redirect-uris.feature, ui-automation-tests/acceptance-features/clients/change-redirect-uris.feature, ui-automation-tests/acceptance-features/clients/change-sector-identifier-uri.feature
Added after a request from an RP developer. HTTP will not be permitted in production [deploy]
> [!WARNING]
-   any …
=> ATO-1337: Allow HTTP urls

package-lock.json
This fixes a low vulnerability
> [!WARNING]
-   [ ] tests have …
=> BAU: Fix vulnerability in cookie package

express/resources/allowed-email-domains.txt, express/src/views/register/enter-email-address.njk
=> add mod.uk to allowlist

express/resources/allowed-email-domains.txt, express/src/views/register/enter-email-address.njk
[AP-470](https://govukverify.atlassian.net/browse/AP-470)
> [!WARNING]
-   any replaced methods are marked as …
=> AP-470 - add ibca.org.uk to the allow list

.github/workflows/test.yml, backend/api/api.template.yml
Sonarcloud action is being deprecated
> [!WARNING]
-   [ ] tests …
=> ATO-1448: Migrate sonarcloud action to sonarqube

.github/workflows/deploy-contract.yml
Add condition to run contract workflow when merging into main.
=> BAU: add condition in GH workflow to run workflow when merging to main

.github/workflows/deploy-branch-to-dev.yml
=> BAU: Create separate action to fix deploy dev workflow

backend/dynamodb/dynamodb.template.yml
=> ATO-1484: apply BackupFrequency tag to client store data table

backend/api/src/handlers/code-block/code-block-handler.ts, backend/api/src/handlers/dynamodb/code-block-service.ts, backend/api/src/handlers/helper/logger.ts
=> BAU: Create singleton logger instance

backend/api/api.template.yml, infrastructure/frontend/frontend.template.yml
Add tags so that FMS can find the resources to add policies to
> [!WARNING]
-   any replaced methods are marked as …
=> ATO-1532: Add FMS tags

backend/api/api.template.yml, infrastructure/frontend/frontend.template.yml
=> BAU: Disassociate waf in build

backend/api/api.template.yml, infrastructure/frontend/frontend.template.yml
=> BAU: Disassociate WAF in staging

backend/api/api.template.yml, infrastructure/frontend/frontend.template.yml
=> ATO-1532: Disassociate waf in integration

backend/api/src/handlers/dynamodb/put-service-client.ts, backend/api/tests/handlers/dynamodb/put-service-client.test.ts, express/@types/client.d.ts, express/src/controllers/clients.ts, express/src/lib/models/client-utils.ts, express/src/routes/clients.ts, express/src/services/lambda-facade/StubLambdaFacade.ts, express/src/views/clients/client-details.njk, express/src/views/clients/enter-max-age.njk, express/tests/constants.ts, express/tests/controllers/clients.test.ts, express/tests/services/lambda-facade/StubLambdaFacade.test.ts, ui-automation-tests/acceptance-features/clients/change-max-age.feature
Adding a way to enabled or disable max age in SSE tool
Have tested in Dev
=> Ato 1102/add max age

backend/api/api.template.yml, infrastructure/frontend/frontend.template.yml
=> ATO-1532: Disassociate waf in production

.github/dependabot.yml
=> BAU: Add missing directories to dependabot config

express/src/middleware/validators/mobile-number-validator.ts
=> BAU: Remove log line

infrastructure/frontend/frontend.template.yml
=> ATO-1823: turn on rebranding feature flag

express/src/controllers/sign-in.ts, express/src/lib/utils/secure-random-code.ts, express/src/middleware/validate-public-key.ts, express/src/services/cognito/CognitoClient.ts, express/tests/controllers/sign-in.test.ts, express/tests/lib/utils/secure-random-code.test.ts, express/tests/services/cognito/cognitoClient.test.ts
=> ATO-1832 address sonar concerns

express/.env.example, express/assets/css/app.scss, express/assets/css/modules/_notification-banner.scss, express/src/app.ts, express/src/config/environment.ts, express/src/views/layouts/base.njk, infrastructure/frontend/frontend.template.yml
=> ATO-1911: add service unavailable notification banner

backend/api/api.template.yml, backend/cognito/cognito.template.yml
=> ATO-1896: upgrade dynatrace in production

.github/dependabot.yml, infrastructure/frontend/Dockerfile
=> ATO-1954: add docker to dependabot

express/assets/css/app.scss, express/src/controllers/clients.ts, express/src/views/clients/client-details.njk, express/tests/constants.ts, express/tests/controllers/clients.test.ts, infrastructure/frontend/frontend.template.yml
=> ATO-1460: remove basic auth credentials
