express/@types/StubCognitoClient/index.d.ts
express/config.json
express/otherConfig.json
express/package.json
express/src/app.ts
express/src/controllers/create-account.ts
express/src/lib/cognito/CognitoClient.ts
express/src/lib/cognito/CognitoInterface.ts
express/src/lib/cognito/StubCognitoClient.ts
express/src/middleware/emailValidator.ts
express/src/middleware/mobileValidator.ts
express/src/routes/create-account-or-sign-in.ts

Provide an alternative implementation of the CognitoClient to enable development and testing without needing an AWS account / tokens
Alter `app.ts` to import the correct CognitoClient based on an environment variable - default to the actual implementation.
Update `package.json` so that the dev script uses StubCognitoClient
Provide a config for the StubCognitoClient so that calls to `createUser` can throw a `UsernameExistsException` if the email address inuse@foo.gov.uk is entered.
Provide an alternative format for the stub config to improve the implementation.  This is noise in this commit but it's a WIP.

Alternative CognitoClient

---

.gitignore
express/@types/OnboardingTableItem/index.d.ts
express/@types/User/index.d.ts
express/src/app.ts
express/src/controllers/create-account.ts
express/src/controllers/manage-account.ts
express/src/lib/lambda-facade/LambdaFacade.ts
express/src/lib/lambda-facade/index.ts
express/src/routes/testing-routes.ts
express/src/views/add-service-name.njk
lambda/dynamo-api/src/handlers/put-service.ts
lambda/dynamo-api/src/handlers/put-user.ts
lambda/dynamo-api/template.yaml

Use LambdaFacade to do call to lambda from frontend.
Facade simplifies the creation of the payload and abstracts away the use of an Axios client to make the calls.  Much of the code that lived in the controller previously moves to the facade.
Add types to make working with TableItems and users easier.
Add cognitoUser to session and selfServiceUser to session - the cognitoUser contains stuff needed for sign-up / sign-in, the selfServiceUser is what gets stored.  Better names and arrangement will hopefully become clear in the future.

DFA-732 Use lambda to store details of user

---

express/@types/Service/index.d.ts
express/package-lock.json
express/package.json
express/src/controllers/manage-account.ts
express/src/controllers/sign-in.ts
express/src/lib/lambda-facade/LambdaFacade.ts
express/src/routes/manage-account.ts
lambda/dynamo-api/src/client/DynamoClient.ts
lambda/dynamo-api/src/handlers/get-user.ts
lambda/dynamo-api/src/handlers/put-service-user.ts
lambda/dynamo-api/src/state-machines/newService.json
lambda/dynamo-api/template-without-swagger.yaml
lambda/dynamo-api/template.yaml

Create lambda to save service
Create lambda to save service-user
Create StepFunction to co-ordinate the running of each of the above lambdas
Create API Gateway configuration to invoke StepFunction wihout JSON containing apostrophes being mangled by AWS into something AWS won't accept.
Create controller to handle the creation of a new service and to call the API Gateway Resource created above.
Keep template.yaml that didn't need a massive verbose API definition so I can shed a tear at how close we were to something elegant and simple.
Update sign-in controller to send us straight to the add-service screen because it's much easier to develop when you only have to sign in and not sign-up every try.
Add necessary functions to LambdaFacade
Add QueryBySortKey to DynamoClient on lambda side as …

DFA-730 save service with lambda

---

express/src/controllers/manage-account.ts
lambda/dynamo-api/src/handlers/put-client.ts
lambda/dynamo-api/src/handlers/put-service-client.ts
lambda/dynamo-api/src/handlers/register-client.ts
lambda/dynamo-api/template.yaml

The data pushed in and out of the lambdas can be refactored neatly and the step function transformations can be used so that only the necessary payloads are passed in.  For the sake of speed this hasn't been done but will definitely need to be refactored at a later date.
Modify register-client.ts lambda to use correct parts of payload when calling Auth API Endpoint. Pass on enough information to put-client for save to DDB to be successful
Modify put-client to take the correct things from input and save to DDB.  Return enough information for next put-service-client.ts lambda to be successful
Modufy put-service-client lambda to store the correct information in DDB.
Modify template.yaml - have putClientFunction use nodejs16.x so that randomUuid is available in the runtime
Modify …

DFA-728 Store Client Details in DynamoDB

---

lambda/dynamo-api/src/handlers/put-service-client.ts
lambda/dynamo-api/src/handlers/register-client.ts
lambda/dynamo-api/src/state-machines/newClient.json
lambda/dynamo-api/template.yaml

Database needs to hold different data because dashboard displays all clients per service.
Remove client-client records - remove put-client lambda.  Update put-service-client to include service details.
Update state machine for new client
Update template.yaml
Would be good to review structure of new service-client record in development account DDB.

DFA-949 Stop using client-client

---

lambda/dynamo-api/src/client/DynamoClient.ts
lambda/dynamo-api/src/handlers/get-services.ts
lambda/dynamo-api/src/handlers/register-client.ts
lambda/dynamo-api/template.yaml

This is branched off DFA-949 because time and tide wait don't wait and neither do I.  Once that's merged this can be rebased etc.
Lambda to query DynamoDB for all services associated with a given user and return as an array of items.
Update DynamoClient with getServices(userId: string) method.  DynamoDB parameters used include ExpressionAttriubteNames to make the whole `pk` and `sk` thing a little less confusing - we create aliases to explain what they represent in this context.
Delete redundant method that promised to marshal a result but did no such thing.
Implement getServiceHandler lamdba.  Return useful 400 response if no userId provided.  In practice I don't think the lambda gets called if the parameter is missing but the thought is there.
Update template.yaml to deploy new lambda.

Dfa 940 get services for user lambda

---

express/@types/User/index.d.ts
express/src/controllers/manage-account.ts
express/src/controllers/sign-in.ts
express/src/lib/lambda-facade/LambdaFacade.ts
express/src/lib/lambda-facade/LambdaFacadeInterface.ts
express/src/lib/lambda-facade/StubLambdaFacade.ts
express/src/routes/manage-account.ts
express/src/views/manage-account/list-services.njk
lambda/dynamo-api/src/handlers/put-service-client.ts

A user logging in will be shown a list of their services unless; they only have one in which case they'll be taken straight to the client screen; they don't have any in which case they'll be taken to the create service screen.
Modify User type - this is to get things working.  We should review everything and figure out where we do our unmarshalling - I expect the answer is in the DDB client.
Modify manage-accounts.ts controllers file.
* List services controller with basic conditional logic to determine whether services are listed, a new one must be created or clients are displayed.
* Extract (our) Client ID from generated client and append to redirect path as parameter.
Modify sign-in.ts - redirect to /account/list-services
Modify Lamdba Facade interface and implementations - add …

DFA-943 list services controller route and view

---

.gitignore
backend/dynamo-api/deploy-script.sh
backend/dynamo-api/template.yaml
backend/dynamo-db/template.yaml
lambda/dynamo-db/template.yaml

Write a template so the correct database table can be deployed to all environments.
Export table name - use stack name as part of export to namespace the tables.
Update lambdas to import the table name and use it.
See commits.

DFA-968 stack for DynamoDB

---

express/src/middleware/urisValidator.ts
express/src/routes/manage-account.ts
express/src/routes/testing-routes.ts

Allow updating of post logout URIs.
Write middleware component that can be used for each redirect-uri configuration value. This contains some truly awful logic but I'm not willing to sit here until 11pm coming up with something nice when we have something that works.
Use middleware for post-logout redirect uris and the normal urs.
Update details using lambda-facade

DFA-916 Update post logout URIs

---

express/src/routes/manage-account.ts
express/src/routes/testing-routes.ts
express/src/views/dashboard/change-user-attributes.njk

Quick solution to save user attributes.  Has messy logic to deal with the delivery of ticked checkboxes and ensure openid is always an option.  We could / should consider displaying nicer versions of the attributes - currently we use the actual attribute names expcted by Auth.  This makes the logic simpler right now but looks a bit odd.
Alter offlineAccess to offline_access in template and route/controllers as that's the parameter the auth API expects.
Add code to call Auth API and update client configuration.
Switch to using join instead of an array.reduce operation.  Barely relevant to this story but I saw we should probably render attributes with a comma-space so made the change everywhere.

DFA-914 Change user attributes

---

express/features/email-verification-resend.feature
express/features/mobile-verification-resend.feature
express/features/support/steps/email-verification-resend-steps.ts
express/features/support/steps/mobile-verification-resend-steps.ts
express/features/support/steps/shared-functions.ts
express/features/support/steps/shared-steps.ts
express/features/support/steps/sign-in-steps.ts
express/features/support/test-setup.ts

- Correctly construct URLs in feature tests 
Avoid failing tests due to double slashes caused by directly adding two strings. Use the URL class instead to handle URL construction.
---
- Remove duplicated code fragments by moving the repeated blocks into functions.
- Apply formatting
- Optimise imports
- Use one kind of quotes for strings (single quotes)

DFA-2030: Apply formatting to the acceptance tests

---

express/assets/css/app.scss
express/assets/css/modules/_side-navigation.scss
express/features/support/steps/shared-functions.ts
express/features/support/steps/shared-steps.ts
express/package.json
express/src/app.ts
express/src/config/configure-views.ts
express/src/views/account/account.njk
express/src/views/account/change-phone-number.njk
express/src/views/account/check-email.njk
express/src/views/common/cookie-banner.njk
express/src/views/create-account/check-email.njk
express/src/views/create-account/get-email.njk
express/src/views/create-account/new-password.njk
express/src/views/create-account/resend-email-code.njk
express/src/views/create-account/resend-phone-code.njk
express/src/views/index.njk
express/src/views/layout.njk
express/src/views/macros/breadcrumbs.njk
express/src/views/resend-phone-code-sign-in.njk
express/src/views/security-check-change-number.njk
express/src/views/service-details/change-public-key-v2.njk
express/src/views/service-details/client-details.njk
express/src/views/service-details/layout-service-details.njk
express/src/views/service-details/private-beta.njk
express/src/views/sign-in-enter-password.njk
express/src/views/sign-in.njk
package-lock.json

- Upgrade to the latest version of the GOV.UK Design System 
See release notes for 4.0.0
https://github.com/alphagov/govuk-frontend/releases/tag/v4.0.0
- Use standard spacing on all views as per the GOV.UK Design System 
Remove custom top and bottom spacing and let the design system handle that.
https://design-system.service.gov.uk/styles/layout/
- Use govuk components where possible instead of HTML

BAU: Upgrade to the latest GOV.UK Design System

---

express/src/app.ts

It appears that error handling was falling through so there were those "already sent the headers" errors.  Move all the error handling inside a single handler which means the next one doesn't get caught.

Tweak error handling

---

.github/workflows/build-front-app.yml
.github/workflows/build-front-image.yml
.github/workflows/check-code-quality.yml
.github/workflows/check-pr.yml
.github/workflows/delete-deployment.yml
.github/workflows/deploy-branch.yml
.github/workflows/deploy-to-paas.yml
ci/github-actions-role.yml
express/assets/css/app.scss
express/src/views/create-account/existing-account.njk

**_Note: This PR needs shared actions from alphagov/di-github-actions#25_**
**DFA-2048: Add a workflow to build and push frontend image to ECR**
The workflow builds and pushes frontend images for preview deployments.
Each image is versioned with the git SHA and additionally has the current branch tag. Since the repository is immutable, only one image per branch is allowed. The previous version for a branch, if it exists, is deleted before pushing a newer one.
Images are built and pushed when a branch is deployed manually (for now).
---
- DFA-2036: Remove custom padding
Use standard design system padding on the 'account already exists' page

DFA-2048: Add workflow to push frontend Docker image to ECR

---

express/src/services/cognito/StubCognitoClient.ts
express/stub/stubs-config.json

Add some stubbed stuff so we can pretend the user entered the wrong password.
Because of the limitations of the stubs we have to use an email for the value to detect.  These will probably be refactored so not much point in doing anything extra.

BAU simulate wrong password

---

express/src/services/lambda-facade/StubLambdaFacade.ts

Default public for stub response is the default used in to register with Auth.  This means the frontend behaves as though it was live.  If the public key is updated, the stub stores the updated value.
Service name is saved in the stub so proper behaviour is replicated.
These are 'good enough' solutions as the stubs are going to be refactored or replaced at some point.

DFA-2281 update stubs for testing

---

express/src/lib/publicKeyUtils.ts
express/tests/lib/publicKeyUtils.test.ts

Do global find and replace on returned public key.
Change logging to only log at the end.
Co-authored by: Karol Gancarz <karol.gancarz@digital.cabinet-office.gov.uk>

BAU Fix public key utils

---

backend/domains/development/template.yaml
backend/domains/production/template.yaml

Create hosted zones for `development.sign-in.service.gov.uk` and `preview.sign-in.service.gov.uk`.
Create hosted zones to be applied in the development account for the development and preview sub domains.
Update the production hosted zone with NS records pointing to the nameservers in the new hosted zones so that queries will resolve properly.
The development and preview templates have been applied and the nameservers can be checked in Route53 to make sure that the production hosted zone is correct in this PR before it is also applied.

SSE-2310 Self Service development domains

---

backend/dynamo-api/package.json
backend/dynamo-api/src/handlers/put-service-client.ts
backend/dynamo-api/src/handlers/register-client.ts
backend/dynamo-api/template.yaml
package-lock.json

Backend changes
Don't add post_logout_redirect_uris to payloads for registering client and creating service-client.
Also add aws-dynamo package which was missing from package.json
No changes made to frontend to avoid merge conflicts with [SSE-2379 - Fix Medium accessibility issues](https://github.com/alphagov/di-onboarding-self-service-experience/pull/198/files#top) - some work will need to be done to conditionally insert 'Not yet added' or something; currently it's just left blank.

SSE-2398 Make Post Logout URLs optional

---

express/src/routes/testing-routes.ts
express/src/services/lambda-facade/StubLambdaFacade.ts
express/src/views/service-details/layout-service-details.njk

`layout-service-details.njk` needs some IDs passed in for some links to work properly.  The Team members page was not being rendered with those values included or with the serviceName which comes from the session.
The Team members route did not include the parameters for `serviceId`, `selfServiceClientId` or `clientId` so it could not render the Change service link properly and couldn't propagate those IDs to the pages referenced in the side bar.
Change the route to include the parameters and make sure they are added to the rendering code so they can be added to URLs.
Change `views/service-details/layout-service-details.njk` so missing IDs are added to the team-members URL as parameters.
Make sure the serviceName held in the session is passed when rendering the Team members page
Update …

SSE-2365 make Change service name work properly

---

express/features/support/steps/client-steps.ts
express/features/update-client.feature
express/src/controllers/manage-account.ts
express/src/routes/testing-routes.ts

Public Key data should be displayed in the text area used for entering public keys and you never know when you'll need to manually edit the public key you've already successfully stored.
Use correctly sanitised version of public key so comparisons work and the default isn't displayed.
Pass value to template.
Add test.

SSE-2386 Public Key not displayed in text area

---

backend/dynamo-api/src/handlers/send-private-beta-notification.ts
express/features/joining-private-beta.feature
express/features/sign-in-unhappy-paths.feature
express/features/sign-in.feature
express/features/sign-up.feature
express/features/support/steps/shared-functions.ts
express/features/support/steps/shared-steps.ts
express/features/support/test-setup.ts
express/features/update-client.feature
express/features/your-account.feature
express/package.json
express/src/config/configure-views.ts
express/src/services/lambda-facade/StubLambdaFacade.ts
package-lock.json
package.json

**Fix timeout issue in private beta acceptance tests when opening a new tab**
The tab would sometimes take longer to open than the specified timeout, resulting in flaky tests.
`Page.waitForTimeout()` is obsolete and should not be used. It is not recommended to wait for a set number of seconds but instead use a waiter method to wait exactly as long it takes for the desired conditions to be met.
_Puppeteer docs reference: https://pptr.dev/api/puppeteer.page.waitfortimeout#remarks_
Replace `waitForTimeout` with `waitForTarget` to wait until the new tab is opened by the current page. When the new tab is open, load the page contents and make it the current page for the text context so that later steps can reference it.
Split the step into smaller steps and add a check to verify the new page's …

SSE-2336: Fix timeout issue in acceptance tests

---

.github/workflows/delete-deployment.yml

Delete the docker image for the branch when closing a PR or running the workflow manually.
[Images are tagged with the branch name when they are deployed](https://github.com/alphagov/di-onboarding-self-service-experience/blob/92635c123b4c1e043a27df6abac0fea2f16cfc66/.github/workflows/deploy-to-fargate.yml#L44), so use that that to identify the image to delete.

DFA-2463: Clean up frontend docker image

---

express/assets/css/app.scss
express/features/support/steps/client-steps.ts
express/features/update-client.feature
express/src/routes/testing-routes.ts
express/src/views/service-details/change-public-key.njk

I should never have rendered the public key inside the textarea.  Now it goes in the right place.

SSE-2386 Display public key above text area, not in it

---

.github/workflows/check-code-quality.yml
.github/workflows/check-pr.yml
.github/workflows/delete-deployment.yml
.github/workflows/deploy-to-fargate.yml
.github/workflows/deploy-to-paas.yml
express/package.json
package-lock.json
package.json

- Run npm security audit on PRs
- Run AWS CloudFormation linter for CF templates in PRs
---
- Remove deprecated package
`@types/puppeteer` is deprecated and is not needed since `puppeteer` provides its own type definitions.
- Update dev packages

SSE-2463: Run npm security audit and cfn-lint on PRs

---

express/features/support/steps/client-steps.ts
express/src/middleware/convertPublicKeyForAuth.ts
express/src/views/service-details/change-public-key.njk

Make sure public key can be rendered if there are inline errors
Make text for "Current public key" strong.

SSE-2386 Show public key when there have been input errors

---

.github/workflows/check-code-quality.yml
.github/workflows/delete-deployment.yml
.github/workflows/deploy-to-fargate.yml
.github/workflows/deploy-to-paas.yml
.github/workflows/run-acceptance-tests.yml
.github/workflows/run-unit-tests.yml
express/Dockerfile
infrastructure/ci/jest.config.ts
tsconfig.eslint.json

As we've added more acceptance tests, they now take more than 5 minutes to run in GHA. However, cucumber only prints output after all the tests have run, so we don't get any indication of progress. This can't really be fixed due to how cucumber works, but it can be improved by running the tests one feature at a time and printing the output after each.
Additionally, report failed features to the step summary.
For the unit tests, use the dedicated github-actions formatter for jest to get automatic reporting with annotations. This is configured by supplying the dedicated config file.
Adjust the global ts config to include all files not covered by any of the subprojects.

SSE-2463: Show progress when running acceptance tests in GitHub Actions

---

express/features/support/steps/client-steps.ts
express/features/update-client.feature
express/src/lib/publicKeyUtils.ts
express/src/middleware/convertPublicKeyForAuth.ts

Because we just manipulated the input to return and assumed that the crypto lib would refuse to convert input with junk after the key there was a bug.
We would append anythng on a new line after `-----END PUBLIC KEY-----` to the key we rendered and stored.
This changes that so that we export the converted key to PEM format and then strip that so it works for Auth.

SSE-2491 Fix Public Key Bug

---

.github/workflows/check-code-quality.yml
.github/workflows/delete-deployment.yml
.github/workflows/deploy-to-fargate.yml
.github/workflows/deploy-to-paas.yml
.github/workflows/run-acceptance-tests.yml

Use the latest docker actions to clean up ECR images.
Use the latest actions across the repo.

SSE-2463: Delete frontend docker image from ECR for a branch

---

.github/workflows/check-code-quality.yml
.github/workflows/check-pr.yml
.github/workflows/delete-deployment.yml
.github/workflows/deploy-branch.yml
.github/workflows/deploy-to-fargate.yml
.github/workflows/deploy-to-paas.yml
.github/workflows/publish.yml
.github/workflows/run-acceptance-tests.yml
infrastructure/api/deploy-sse-api.sh
infrastructure/check-aws-account.sh
infrastructure/ci/apply-github-role.sh
infrastructure/ci/github-actions-role.yml
infrastructure/deploy-sam-stack.sh
infrastructure/domains/apply-signin-domains.sh
infrastructure/domains/development-domains.yml
infrastructure/domains/integration-domains.yml
infrastructure/domains/production-domains.yml
infrastructure/domains/staging-domains.yml
infrastructure/frontend/apply-frontend-infrastructure.sh
infrastructure/frontend/sse-frontend-infrastructure.yml

**Add a deployment bucket and additional permissions to the GitHub Actions role**
More permissions are needed to deploy the API lambdas.
A SAM deployment bucket needs to be set up in the account before deployments can be done.
Add a check for the frontend infra stack and the OIDC provider, as the template will need to be used in different envs with different requirements.
_Ignore a bunch of checkov warnings for now - we will deal with them later._
---
- Set concurrency for deployments based on the environment
Avoid unnecessary blocking of deployments in different environments.
- Move the logic to check the authenticated AWS account to a separate script
Encapsulate the logic in one script and reuse in deployment scripts.
- Use boolean vars when deploying SAM stacks so they can be picked up …

SSE-2496: Set up a SAM deployment bucket and add permissions to the GHA role

---

express/src/views/service-details/layout-service-details.njk

- Removed the "Team members" link from client details page. It is not needed for MVP.

removing team members for MVP

---

infrastructure/api/sse-api.yml

Deploying stacks with devplatform requires two extra parameters:
*	`PermissionsBoundary`
*	`CodeSigningConfigArn`
These parameter values are supplied by the secure pipeline deployers and are not applied (`AWS::NoValue`) if the parameter is not passed in.
They need to be added to all Lambdas as they create impicit roles and and custom roles that are created like our `StepFunctionExecutionRole`.  I've used Global for the lambdas but global cannot be used for roles.

SSE-2467 template changes for devplatform

---

express/src/lib/clientUtils.ts

Post logout redirect URIs became optional and as a result an empty database will not supply a value for them meaning clients can't be displayed because the frontend tries to do `.split(" ")` on an `undefined` value.
This ensures that if `client.post_logout_redirect_uris` are not returned, an empty array is returned instead.

SSE-2553: Bugfix Post logout redirect URIs

---

backend/cognito/template.yaml

The verification email should have the EmailSendingAccount set to DEVELOPER with the required properties instead of COGNITO_DEFAULT which doesn't use our email address and has a daily limit on the number of emails that can be sent.

SSE-2565 Change email sending to DEVELOPER

---

acceptance-tests/support/steps/shared-steps.ts
acceptance-tests/support/test-setup.ts
acceptance-tests/tsconfig.json
backend/api/src/dynamodb-client.ts
backend/api/tsconfig.json
express/assets/javascripts/cookies.js
express/src/app.ts
express/src/config/session-storage.ts
express/src/lib/AuthenticationResultParser.ts
express/src/lib/clientUtils.ts
express/src/lib/validators/urisValidator.ts
express/src/middleware/request-context.ts
express/src/middleware/validators/mobileOtpValidator.ts
express/src/services/cognito/StubCognitoClient.ts
express/src/services/lambda-facade/StubLambdaFacade.ts
express/src/services/self-service-services-service.ts
express/src/types/request.d.ts
express/tests/middleware/validators/mobileOtpValidator.test.ts
express/tsconfig.json
infrastructure/api/deploy-sse-api.sh
tsconfig.json

**Use the latest TypeScript libraries**
Use ES2022 instead of ES2020 to get the latest features and APIs.
Update TypeScript config to include more compiler checks.
---
**Use the nullish coalescing operator**
Use the nullish coalescing operator instead of the boolean `OR` when dealing with null or undefined values to provide a default value. The boolean `||` operator should only be used in boolean logic to evaluate an expression to `true` or `false`. Use the `??` operator to provide a value when a variable is null or undefined, or `??=` to assign a default value.
---
- Extend timeout for external links in acceptance tests to reduce flaky fails
- Fix optional value handling in the API script
- Simplify request context types; remove unnecessary custom handler

BAU: Use latest TypeScript libraries

---

express/src/lib/commonPasswords/CommonPasswords.ts
express/src/lib/commonPasswords/commonPasswordsSingleton.ts
express/src/lib/publicKeyUtils.ts
express/src/lib/validators/allowed-email-domains.ts
express/src/lib/validators/checkOtp.ts
express/src/lib/validators/emailValidator.ts
express/src/lib/validators/password-validator.ts
express/src/lib/validators/uris-validator.ts
express/src/middleware/validators/emailOtpValidator.ts
express/src/middleware/validators/emailValidator.ts
express/src/middleware/validators/mobileOtpValidator.ts
express/src/middleware/validators/notOnCommonPasswordListValidator.ts
express/src/middleware/validators/passwordValidator.ts
express/src/middleware/validators/urisValidator.ts
express/tests/lib/allowed-email-domains.test.ts
express/tests/lib/commonPasswords.test.ts
express/tests/lib/validators/checkOtp.test.ts
express/tests/lib/validators/emailValidator.test.ts
express/tests/lib/validators/passwordValidator.test.ts
express/tests/lib/validators/urisValidator.test.ts

- Add a validator for allowed domains to encapsulate the logic for verifying emails
- Use default exports in validators
- Streamline the logic and trim down the code
---
- Common passwords validator - export a function instead of a class
- Public key utils - extract the key content and wrap it in headers to ensure whitespace and newlines inside the key are removed

BAU: Update validators

---

express/.env.example
express/package.json
express/src/app.ts
express/src/config/environment.ts
express/src/config/express.ts
express/src/config/session-storage.ts
express/src/controllers/clients.ts
express/src/controllers/services.ts
express/src/controllers/sign-in.ts
express/src/routes/register.ts
express/src/services/cognito/CognitoClient.ts
express/src/services/cognito/CognitoInterface.ts
express/src/services/cognito/StubCognitoClient.ts
express/src/services/lambda-facade/LambdaFacade.ts
express/src/services/lambda-facade/LambdaFacadeInterface.ts
express/src/services/lambda-facade/StubLambdaFacade.ts
express/src/services/self-service-services-service.ts

Tidy up clients for Cognito and Lambda
Add methods to send requests and use them in all functions for consistent usage
Remove unnecessary return types and async, or return void if the output is not used
Add config for env vars to manage them all in one place and set defaults as needed

BAU: Update Cognito and Lambda clients

---

backend/cognito/src/handlers/password-reset-custom-message.ts

Amend path in reset password email that wasn't updated when the routes were rearranged.

SSE-2623 Fix broken link for password reset

---

infrastructure/api/sse-api.yml

More permission are needed for the step function to be able to log to a specific log group.

BAU add missing permissions to StepFunctionExecutionPolicy

---

backend/cognito/email-identity-template.yml
backend/cognito/template.yml

We need to export the domain too - it's coupled with the identity created so it makes sense; it then reduces the required parameters for the actual cognito template.

SSE-2622 Export the actual domain

---

backend/api/src/handlers/auth/register-client.ts
backend/api/src/handlers/auth/update-client.ts
infrastructure/api/sse-api.yml

- Add header for Auth API key
- Add env var for the key
The lambdas should really be using the SSM SDK to access the secret directly rather than store it in the env and expose it. Raising this for now so we can complete testing.

SSE-2549: Add Auth API key config for lambdas using the Auth API

---

infrastructure/ci/development-stacks/deploy-development-stack.sh

The script which sets a new developer up with a set of working stacks broke because the `check-aws-account.sh` got replaced with something else.
Fix that.

BAU Fix broken script

---

express/src/views/clients/change-user-attributes.njk
express/src/views/clients/client-details.njk

Update the dashboard to indicate that OpenID is always a required attribute

SSE-2679 - Update the dashboard to indicate that OpenID is always a required attribute

---

backend/api/api.template.yml
backend/cognito/cognito.template.yml
backend/dynamodb/dynamodb.template.yml
express/.env.example
express/src/config/environment.ts
express/src/config/session-storage.ts
express/src/services/cognito/CognitoClient.ts
infrastructure/aws.sh
infrastructure/ci/configure-deployment-parameters.sh
infrastructure/ci/secure-pipelines/deploy-support-stacks.sh
infrastructure/ci/secure-pipelines/deployment-pipelines.template.yml
infrastructure/ci/secure-pipelines/deployment-support.template.yml
infrastructure/ci/secure-pipelines/empty-buckets.sh
infrastructure/dev/README.md
infrastructure/dev/deploy.sh
infrastructure/frontend/frontend.template.yml
package.json

**Update developer deployment script**
_"It just works"_
Make it easier to use the script to deploy and manage local stacks.
🆕 Add new commands to list and delete stack sets
🆕 Automatically authenticate to AWS if credentials are not present in the environment
🆕 Export the default AWS region to the environment
- Update parameters and environment variables
**Update pipeline and support stacks**
- Add container signer to the development account
- Don't pass allowed accounts in development, since it has no accounts it promotes to
- Pass in the initial account param directly
- Add a container signer in the development account
  A separate resource is needed since in the dev account we deploy our own OIDC provider stack, which the container signer stack cannot depend on. The conditions select …

SSE-2685: Update development deployment scripts

---

.github/workflows/build-api.yml
.github/workflows/build-cognito.yml
.github/workflows/deploy-branch-secure-pipelines.yml
.github/workflows/upload-api-package.yml
.github/workflows/upload-cognito-package.yml
.github/workflows/upload-dynamodb-package.yml
acceptance-tests/package.json
backend/api/package.json
backend/cognito/package.json
express/package.json
express/src/config/session-storage.ts
express/src/types/session-data.d.ts
infrastructure/ci/secure-pipelines/configure-github-repo.sh
infrastructure/ci/secure-pipelines/deployment-pipelines.template.yml
infrastructure/deploy-sam-stack.sh
infrastructure/dev/README.md
infrastructure/dev/deploy.sh
package-lock.json
package.json

**Await CodePipeline execution after uploading SAM packages to secure pipelines**
Use the `secure-pipelines/deploy-application` action that will cause the GitHub Actions job to keep spinning for each component until its pipeline finishes with a success or failure state.
The deployer roles need to be given permission to list their pipelines' executions.
---
- Show pipeline URL in the GitHub Actions UI
- Update `PipelineEnvironentNameEnabled` param as the typo has been fixed
- Don't export region in deployment scripts
The `gds-cli` exports the region environment variables as of [version 5.75.0](https://github.com/alphagov/gds-cli/releases/tag/v5.75.0)
There's no longer a need to set this manually.
- Update dev script
Show all stacks with a partial prefix
- Update packages
Update session …

SSE-2685: Secure pipelines - await deployment to complete in GHA

---

backend/cognito/cognito.template.yml
express/src/services/self-service-services-service.ts
infrastructure/ci/configure-deployment-parameters.sh

Even though we use a custom lambda to send the MFA code, we still need to leave MFA enabled in the User Pool.
Enabling the option requires providing SMS config, even it's not used.

SSE-2672: Turn on Cognito MFA and restore SMS config

---

.github/workflows/check-code-quality.yml
acceptance-tests/features/account.feature
acceptance-tests/features/clients.feature
acceptance-tests/features/register.feature
acceptance-tests/features/services/joining-private-beta.feature
acceptance-tests/features/services/update-service-name.feature
acceptance-tests/features/sign-in.feature
acceptance-tests/support/steps/shared-steps.ts
express/resources/allowed-test-domains.txt
express/src/config/environment.ts
express/src/config/resources.ts
express/src/lib/validators/allowed-email-domains.ts
express/src/routes/testing.ts
express/src/services/lambda-facade/StubLambdaFacade.ts
express/stubs/stubs-config.json
express/tests/lib/validators/email-validator.test.ts

Set the allowed emails domains source file in the environment, with default to a non-prod version. For consistency refactor the common password file for the same pattern, but currently no need for non-prod version.

Allow prod and nonprod to have different allowed email domins

---

backend/api/api.template.yml
backend/cognito/cognito.template.yml
backend/dynamodb/dynamodb.template.yml
infrastructure/ci/configure-deployment-parameters.sh
infrastructure/dev/deploy.sh
infrastructure/frontend/frontend.template.yml

**Make the backend API private by default**
When the frontend runs in the VPC, it can only communicate with the backend API Gateway via a VPC endpoint, meaning the endpoint must be set to private and the VPC subnets needs to be provided.
When running the frontend locally, we need the API to be public, so add a param to enable that and not set the private endpoint config.
Note that the API URL is different when executed through a VPC endpoint, hence the conditional on the output value.
Use a REST API as it's the only one that supports private endpoints.
**Update the frontend template**
- Set up ECS service
- Add container logs
- Add ECS params & env vars
- Add Cognito permissions
- Set up container healtcheck
- Don't assign public IP to frontend service as we'll be using API Gateway and …

SSE-2638: Add an option to make the backend API private

---

infrastructure/config/network.template.yml

Enable traffic to CloudFront as it's used by Notify
Add a temporary param to export firewall subnets as this is awaiting a change from devplatform

SSE-2649: Enable Notify API in the VPC

---

backend/cognito/tests/handlers/security-code-text-message-sender.test.ts
backend/cognito/tests/mocks.ts

Apply common patterns and best practices to the SMS sender lambda from other unit tests
- When creating mocks, only hold references to things that need to be used in the tests
- Set up the mock for `smsSenderTrigger` in a separate file for reuse - use a double type assertion to create an "optional" type and avoid having to specify all the properties each time
- Use `expect....rejects` to check that an async function throws an error instead of `try....catch`

SSE-2735: Cognito SMS sender test

---

.github/workflows/check-pr.yml
.github/workflows/clean-up-deployments.yml
.github/workflows/delete-deployment.yml
.github/workflows/deploy-branch.yml
.github/workflows/deploy-component.yml
.github/workflows/deploy-to-paas.yml
infrastructure/frontend/frontend.template.yml

- Deploy branch preview to AWS on pull requests
- Set the deployment URL to the URL of the deployed Admin Tool instance
- Rename "preview" environment to "PaaS" to reflect the fact that previews go to AWS and PaaS is used only for acceptance tests

SSE-2063: Set frontend deployment URL

---

.github/workflows/deploy-component.yml
backend/cognito/cognito.template.yml
infrastructure/ci/development/deployment-config.template.yml
infrastructure/config/network.template.yml

- Export VPC endpoints security group from the VPC stack
- Use the VPC endpoints security group so lambdas can access AWS services
- Use private subnets as default for Cognito lambdas
- Use the AWS managed policy to allow VPC lambda access
- Override the subnet for the lambda that needs access to external endpoints
- Add permissions for the GitHub Actions role to configure VPC for lambdas

SSE-2649: Add VPC config to Cognito lambdas

---

.github/workflows/build-frontend-image.yml
.github/workflows/deploy-branch.yml
.gitignore
infrastructure/ci/development/deployment-config.template.yml
infrastructure/ci/secure-pipelines/deployment-pipelines.template.yml
infrastructure/dev/deploy.sh
infrastructure/frontend/Dockerfile
infrastructure/frontend/frontend.template.yml
package-lock.json
package.json

- Github workflows
- In order to log into the dynatrace repo a PaaS token will be required and a GitHub secret, DYNATRACE_PAAS_TOKEN  creating. Information on creation of the token is here https://github.com/govuk-one-login/observability-infrastructure/tree/main/fargate#building-the-container.
- gitignore for vscode
- Cloudformation Templates
- Giving the deployment IAM role permission to pull the secrets from di-observability-prod secrets manager
- Pulling the values needed from the secrets
- Dockerfile change to pull the One Agent from Dynatrace container registry
Notes
- bash script needs to receive the PaaS token in someway and then authenticate against the registry. The line is there but commented out.
- Doc and what we are trying to do …

OBS-31 Add the Dynatrace one agent to the frontend containe

---

acceptance-tests/features/register.feature
acceptance-tests/features/sign-in.feature
acceptance-tests/support/steps/input-steps.ts
express/src/controllers/register.ts
express/src/services/cognito/StubCognitoClient.ts
package-lock.json

Currently, we do not have tests for covering the scenarios 
When a user tries to register with an expired security digit i.e., received in an email 
When a user tries to sign in with an expired security digit i.e., received on mobile 
Relevant stubs to be implemented for covering these scenarios

SSE-2995:Stubs required for covering the scenarios related to Expired Security Digit

---

express/assets/css/app.scss
express/assets/javascripts/cookies.js
express/assets/javascripts/toggle-public-key-view.js
express/src/config/helmet.ts
express/src/views/404.njk
express/src/views/clients/client-details.njk
express/src/views/components/cookie-banner.njk

Remove styleSrc:'unsafe-inline' from helmet configuration and update the application accordingly - not to use inline styles

SSE-3061 - Remove styleSrc:'unsafe-inline' from helmet

---

infrastructure/config/network.template.yml

Support team is moving from Zendesk to ServiceNow for handling support tickets, this is why we need to integrate ServiceNow with “Contact us“ form on Product Pages website.

SSE-3131:Amend Network Template to open traffic in AWS to ServiceNow Endpoint

---

backend/api/src/handlers/auth/register-client.ts
backend/api/src/handlers/auth/update-client.ts
backend/api/src/handlers/dynamodb/put-service-client.ts
backend/api/tests/handlers/auth/register-client.test.ts
backend/api/tests/handlers/auth/update-client.test.ts
backend/api/tests/handlers/constants.ts
backend/api/tests/handlers/dynamodb/dynamo-db-service.test.ts
backend/api/tests/handlers/dynamodb/get-service-clients.test.ts
backend/api/tests/handlers/dynamodb/get-services.test.ts
backend/api/tests/handlers/dynamodb/get-session-count.test.ts
backend/api/tests/handlers/dynamodb/get-user.test.ts
backend/api/tests/handlers/dynamodb/global-sign-out.test.ts
backend/api/tests/handlers/dynamodb/put-service-client.test.ts
backend/api/tests/handlers/utils.ts
express/@types/client.d.ts
express/src/controllers/clients.ts
express/src/lib/models/client-utils.ts

- Storing the `token_authentication_method` value in the table
- Adds custom types to `updateClientInRegistryHandler` and `registerClientHandler` as handlers are invoked by step function not API Gateway. 
- Adds `token_endpoint_auth_method` to respective types
- Adds test utility `backend/api/tests/handlers/utils.ts ` to create ApiGatewayEvents
- Adds some more dynamoDb handler unit tests from Branch `SSE-3125-api-dynamodb-unit-tests`
- Adds conditional display of PublicKey vs clientSecret depending on the `token_authentication_method`
- Refactors some tests to remove `ts-ignore` comments 
- N/A
> [!NOTE]  
> Most of the code changes in this PR are contained in unit tests, happy to remove this as the diff is quite large

SSE-3234: Backend support for "Client authentication" section in the Client page of Admin Tool

---

express/package.json
package-lock.json

- N/A
- Bumps express to version 4.19.2, as older versions of express have a vulnerability when using `res.redirect()`
https://github.com/advisories/GHSA-rv95-896h-c2vc
- N/A

BAU: bump express to 4.19.2

---

backend/api/api.template.yml
backend/api/src/handlers/auth/update-client.ts
backend/api/src/handlers/dynamodb/update-service-client.ts
backend/api/src/handlers/dynamodb/update-service.ts
backend/api/src/handlers/step-functions/new-client.ts
backend/api/src/handlers/step-functions/new-service.ts
backend/api/src/handlers/step-functions/step-function-handler.ts
backend/api/src/handlers/step-functions/update-client.ts
backend/api/src/handlers/step-functions/update-service.ts
backend/api/state-machines/update-service.json
backend/api/tests/handlers/dynamodb/update-service.test.ts
backend/api/tests/handlers/step-functions/update-service.test.ts
express/src/controllers/clients.ts
express/src/services/lambda-facade/LambdaFacade.ts
express/src/services/lambda-facade/LambdaFacadeInterface.ts
express/src/services/lambda-facade/StubLambdaFacade.ts
express/src/services/self-service-services-service.ts

SSE-3309 - sync service name changes with client name in Client Registry when updated. Adds new step function, api configuration and unit test. Refactoring common code in the step functions. Adds extra parameter required from Frontend.

SSE-3309 - sync service name changes in Client Registry

---

express/src/controllers/account.ts
express/src/controllers/sign-in.ts
express/tests/constants.ts
express/tests/controllers/account.test.ts
express/tests/controllers/sign-in.test.ts
express/tests/middleware/process-sign-in-form.test.ts
express/tests/middleware/sign-in-middleware.test.ts
express/tests/mocks.ts

> [!NOTE]  
> This PR makes two small production code changes in the following commits: [FIX: Adds errorMessages object](https://github.com/govuk-one-login/onboarding-self-service-experience/pull/708/commits/b4858d5f14e221558ff7b7ddc9dc109480fd73e2), and here [FIX: Adds errorMessages to the options object used in error handling](https://github.com/govuk-one-login/onboarding-self-service-experience/pull/708/commits/38eb76b86fceaf6a0efc5a562a213f8ad27e8fe0). 
- Unit tests where they are missing for the `sign-in.ts` and `account.ts` controllers
- Two small code changes in the `changePassword` controller and `forgotPassword` controller. These add an errorMessages property on an options object to resolve a runtime TypeError
- Some of the existing Unit tests as I have moved the mock S4 instance …

BAU: `sign-in` and `accounts` controller unit tests

---

backend/cognito/package.json
package-lock.json

ATO-999: Update AWS Crypto

---

express/src/services/lambda-facade/LambdaFacade.ts
express/src/services/lambda-facade/LambdaFacadeInterface.ts
express/src/services/self-service-services-service.ts
express/tests/services/lambda-facade/LambdaFacade.test.ts
express/tests/services/self-service-services-service.test.ts

This will allow us to ensure the correct user is making the call in a subsequent change
> [!WARNING]
-   any replaced …

INCIDEN-922: Send access token to list client API

---

backend/api/src/dynamodb-client.ts
backend/api/src/handlers/dynamodb/get-service-clients.ts
backend/api/tests/handlers/constants.ts
backend/api/tests/handlers/dynamodb/get-service-clients.test.ts
backend/api/tests/handlers/utils.ts

INCIDEN-922: Restricting list client API action to specified user

---

backend/api/api.template.yml
backend/api/src/handlers/dynamodb/get-service-clients.ts
backend/api/src/handlers/helper/validate-authorisation-header.ts
backend/api/src/handlers/step-functions/update-service.ts
backend/api/tests/handlers/constants.ts
backend/api/tests/handlers/step-functions/update-service.test.ts
backend/api/tests/helper/validate-authorisation-header.test.ts

Add checks to updateService to allow access.
Replicating the service and user check in the ListClient to the updateService. As some forms dont call the ListClient this is another layer of protection in assuring the user has access to the client update.

Ato 1022 fix update service access

---

backend/api/api.template.yml
backend/api/src/dynamodb-client.ts
backend/api/src/handlers/dynamodb/dynamo-db-service.ts
backend/api/src/handlers/dynamodb/get-services.ts
backend/api/src/handlers/dynamodb/get-user.ts
backend/api/src/handlers/dynamodb/update-service-client.ts
backend/api/src/handlers/dynamodb/update-service.ts
backend/api/src/handlers/dynamodb/update-user.ts
backend/api/src/handlers/step-functions/update-client.ts
backend/api/tests/dynamodb-client.test.ts
backend/api/tests/handlers/dynamodb/dynamo-db-service.test.ts
backend/api/tests/handlers/dynamodb/get-services.test.ts
backend/api/tests/handlers/dynamodb/get-user.test.ts
backend/api/tests/handlers/dynamodb/update-user.test.ts
backend/api/tests/handlers/step-functions/update-client.test.ts
express/src/controllers/register.ts
express/src/services/lambda-facade/LambdaFacade.ts
express/src/services/lambda-facade/LambdaFacadeInterface.ts
express/src/services/self-service-services-service.ts
express/tests/constants.ts
express/tests/controllers/register.test.ts
express/tests/services/lambda-facade/LambdaFacade.test.ts
express/tests/services/self-service-services-service.test.ts

INCIDEN-922: further access control

---

express/src/controllers/clients.ts
express/src/views/clients/client-details.njk
express/tests/constants.ts
express/tests/controllers/clients.test.ts
infrastructure/frontend/frontend.template.yml
ui-automation-tests/acceptance-features/clients/client-details.feature

- Derives basic auth credentials from environment variables when generating static content
- These are stored in secrets manager and pulled in at deploy time in the task definition 
- Removes any hardcoded values from the tests and pulls these in from ssm when the test container is ran
- Removes basic auth credentials from hardcoded content  and tests
Two secrets needs to be manually created in each environment before this is deployed

ATO- 1063 basic auth secret

---

express/src/lib/validators/allowed-email-domains.ts
express/tests/lib/validators/allowed-email-domains.test.ts
express/tests/lib/validators/email-validator.test.ts

Previously, if slc.co.uk were on the allowlist notslc.co.uk would also be permitted

BAU: Prevent evil domain substrings

---

.github/workflows/deploy-contract.yml
backend/api/tests/contract-tests/package.json
backend/api/tests/contract-tests/src/connect.ts
backend/api/tests/contract-tests/src/publish.ts

Uploading the contract test to the pact broker. This has been tested uploading to the dev pact broker and also main. You can see on the Prod pact broker. 
Also added the needed secrets to this repo for the workflow to be able to connect and publish to the pact broker.

Ato 1239/upload to pact broker

---

backend/api/api.template.yml
backend/api/src/handlers/code-block/code-block-handler.ts
backend/api/src/handlers/dynamodb/code-block-service.ts
backend/api/src/handlers/helper/getEnv.ts
backend/api/src/handlers/types/code-block-entry.ts
backend/api/src/handlers/types/handler-env-var.ts
backend/api/tests/handlers/code-block/code-block-handler.test.ts
backend/api/tests/handlers/service/code-block-service.test.ts
backend/dynamodb/dynamodb.template.yml
express/package.json
express/src/controllers/register.ts
express/src/services/lambda-facade/LambdaFacade.ts
express/src/services/lambda-facade/LambdaFacadeInterface.ts
express/src/services/lambda-facade/StubLambdaFacade.ts
express/src/services/self-service-services-service.ts
express/src/types/code-block-response.ts
express/src/types/session-data.d.ts
express/src/views/register/too-many-codes.njk
express/tests/controllers/register.test.ts
express/tests/mocks.ts
express/tests/services/lambda-facade/LambdaFacade.test.ts
package-lock.json
package.json
ui-automation-tests/acceptance-features/register.feature

When registering with the SSE tool, you receive an email OTP code. There was previously no rate limit on submitting these, so it was plausible to enumerate through all possible values.
This PR adds two safeguards to this:
- A session side check in which a count is incremented every time a  incorrect code is submitted
- A backend check where the hashed email is stored against a 1 hour ttl. This is triggered when the user submits 6 incorrect OTP codes.
- Introduced a session side check for emailCode request count which is incremented when an incorrect code is submitted
- Introduces a new dynamo table backend lambda for code request blocking. This has been left fairly generic so it could be potentially applied to other things in the future. This table will store the hashed email with a …

ATO-1445: Adds rate limit to email otp codes

---

backend/api/api.template.yml
backend/api/package.json
backend/cognito/cognito.template.yml
package-lock.json
package.json

- Tested on the dev environment, ran through the following journey's successfully:
- _API version bump:_
- Full sign up journey
- Full sign in journey
- _Cognito lambda version bump:_
- SMS OTP sending (tests `SendSecurityCodeTextMessageFunction`)
- Full password change journey (request reset, perform reset)
- Tests `CreatePasswordResetMessageFunction`
- Tests `SendPasswordChangedEmailFunction` (note that no email was received as this functionality [has been disabled](https://github.com/govuk-one-login/onboarding-self-service-experience/commit/3e08b97dbf5a694f8292decbfb3968fa9728467d), the lambda or wider system did not experience any errors though).
- Acceptance tests (fairly comprehensive) passing.
> [!WARNING]
> Pull requests merged to `main` will be released to production, please …

ATO-1483: upgrade node runtime from 18 to 22

---

package-lock.json
ui-automation-tests/package-lock.json
ui-automation-tests/package.json

Bumps puppeteer to version 22.15.0 to resolve a vulnerability on in tar-fs[1]. Have looked at the changelog and can see this doesn't include any breaking changes. Also ran `npm update tar-fs 3.0.8` to ensure this was fully updated
This change also pins puppeteer as it was not perviously pinned which made this harder to debug locally. I think we should check that packages are pinned more generally in this repo
[1]- https://github.com/govuk-one-login/onboarding-self-service-experience/security/dependabot/88
-   all methods signatures and return values are …

BAU: Bump puppeteer and pin version

---

backend/api/src/handlers/dynamodb/put-service-client.ts
backend/api/tests/handlers/dynamodb/put-service-client.test.ts
express/@types/client.d.ts
express/src/controllers/clients.ts
express/src/lib/models/client-utils.ts
express/src/routes/clients.ts
express/src/services/lambda-facade/StubLambdaFacade.ts
express/src/views/clients/change-pkce-enforced.njk
express/src/views/clients/client-details.njk
express/tests/constants.ts
express/tests/controllers/clients.test.ts
express/tests/services/lambda-facade/StubLambdaFacade.test.ts
ui-automation-tests/acceptance-features/clients/change-pkce-enforced.feature
ui-automation-tests/support/steps/clients-steps.ts

-   [x] tests have been written to cover any new or updated functionality
-   [x] new configuration parameters have been deployed to all environments, see [configuration management](https://govukverify.atlassian.net/l/cp/N7q3Vh3r).
-   [x] all external infrastructure dependencies have been updated in all environments
Added PKCE Enforced to the client registry, in which if enabled the request must use the code_challenge

Ato 1493 add pkce enforced client registry

---

package-lock.json

- update brace-expansion to 1.1.12 and 2.0.2 to fix [this vulnerability](https://github.com/govuk-one-login/onboarding-self-service-experience/security/dependabot/96)
- brace-expansion is a dependency of pact and ts-jest, it is not a production dependency

BAU Patch brace-expansion vulnerability

---

express/@types/client.d.ts
express/src/controllers/clients.ts
express/src/lib/models/client-utils.ts
express/src/routes/clients.ts
express/src/services/lambda-facade/StubLambdaFacade.ts
express/src/views/clients/change-landing-page-url.njk
express/src/views/clients/client-details.njk
express/src/views/clients/enter-identity-verification.njk
express/tests/constants.ts
express/tests/controllers/clients.test.ts
express/tests/services/lambda-facade/StubLambdaFacade.test.ts
infrastructure/frontend/frontend.template.yml
ui-automation-tests/acceptance-features/clients/change-identity-verification.feature
ui-automation-tests/acceptance-features/clients/change-landing-page-uri.feature
ui-automation-tests/support/steps/clients-steps.ts
ui-automation-tests/support/steps/input-steps.ts

RPs should have a landing page url registered if they are going to use identity verification. The ability to add landing page url to client config is being [added to authentication api](https://github.com/govuk-one-login/authentication-api/pull/6715)
- add landingPageUrl to the 'Manage client' settings on Manage service page, with a corresponding page for updating landingPageUrl
- add hint text to the enable identity verification page to explain the need for landing page url
- conditionally add reminder about landing page url to the success banner when identity verification enabled
- generate success banner text in the controller to avoid complex logic in the template
NB: `landingPageUrl` is the term used in the Client Registry so this term is used in the SSE code. However, in the UI …

ATO-1730/Allow RP to set landing page url

---

backend/api/tests/contract-tests/package-lock.json
backend/api/tests/contract-tests/package.json
package-lock.json
package.json

- a [critical vulnerability](https://github.com/govuk-one-login/onboarding-self-service-experience/security/dependabot/102) has been identified in form-data versions <4.0.4 and <2.5.4 used by axios and pact-node respectively
- axios is not yet patched so overriding to patched form-data version 4.0.4
- looking into possible updates for pact-node, in the meantime overriding form-data to the patched version 2.5.4 for contract tests
- will update axios and pact when possible and remove the override
Testing in dev - client updates rely on axios - these were successful.

BAU: Override form-data version for axios to resolve vulnerability

---

package-lock.json
package.json

Context: `axios` depends on `form-data` which had a critical vulnerability, so the version of 'form-data' was [overridden](https://github.com/govuk-one-login/onboarding-self-service-experience/pull/1097) while waiting for axios to be updated. Now axios has been updated to use the patched version of `form-data' (4.0.4).
- update `axios` to the patched version and remove the redundant override relating to `form-data`.

ATO-1861: Bump axios and remove redundant override

---

express/src/controllers/account.ts
express/src/controllers/register.ts
express/src/views/common/enter-text-code.njk
express/tests/controllers/account.test.ts
express/tests/controllers/register.test.ts

ATO-1998: add back button links to enter-text-code pages

---

backend/api/tests/contract-tests/package-lock.json
backend/api/tests/contract-tests/package.json
package-lock.json
package.json

- Pino versions prior to 9.12.0 were depending on `fast-redact`, which was vulnerable to prototype pollution (https://github.com/govuk-one-login/onboarding-self-service-experience/security/dependabot/107). 
- [Pino v9.12.0](https://github.com/pinojs/pino/releases/tag/v9.12.0) replaces `fast-redact` with `slow-redact`, so i've set this as the minimum version

BAU: Update minimum pino version
